export const FORMATIONS = {
  "4-4-2": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["lw", "lcmf", "rcmf", "rw"],
    ["ss", "cf"],
  ],
  "4-2-3-1": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["ldmf", "rdmf"],
    ["lamf", "amf", "ramf"],
    ["cf"],
  ],
  "4-3-3": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["lcmf3", "dmf", "rcmf3"],
    ["lwf", "cf", "rwf"],
  ],
  "4-2-2-2": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["ldmf", "rdmf"],
    ["lamf", "ramf"],
    ["ss", "cf"],
  ],
  "3-5-2": [
    ["gk"],
    ["lcb3", "cb", "rcb3"],
    ["lwb", "lcmf3", "dmf", "rcmf3", "rwb"],
    ["ss", "cf"],
  ],
  "3-4-3": [
    ["gk"],
    ["lcb3", "cb", "rcb3"],
    ["lwb", "lcmf", "rcmf", "rwb"],
    ["lwf", "cf", "rwf"],
  ],
  "4-4-1-1": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["lw", "lcmf", "rcmf", "rw"],
    ["amf"],
    ["cf"],
  ],
  "4-2-1-3": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["ldmf", "rdmf"],
    ["amf"],
    ["lwf", "cf", "rwf"],
  ],
  "4-1-4-1": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["dmf"],
    ["lw", "lcmf", "rcmf", "rw"],
    ["cf"],
  ],
  "4-4-1": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["lw", "lcmf", "rcmf", "rw"],
    ["cf"],
  ],
  "5-4-1": [
    ["gk"],
    ["lb5", "lcb3", "cb", "rcb3", "rb5"],
    ["lw", "lcmf", "rcmf", "rw"],
    ["cf"],
  ],
  "5-3-2": [
    ["gk"],
    ["lb5", "lcb3", "cb", "rcb3", "rb5"],
    ["lcmf3", "dmf", "rcmf3"],
    ["ss", "cf"],
  ],
  "3-4-1-2": [
    ["gk"],
    ["lcb3", "cb", "rcb3"],
    ["lwb", "lcmf", "rcmf", "rwb"],
    ["amf"],
    ["ss", "cf"],
  ],
  "5-3-0": [
    ["gk"],
    ["lb5", "lcb3", "cb", "rcb3", "rb5"],
    ["lcmf3", "dmf", "rcmf3"],
  ],
  "4-3-1-2": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["lcmf3", "dmf", "rcmf3"],
    ["amf"],
    ["ss", "cf"],
  ],
  "3-4-2": [
    ["gk"],
    ["lcb3", "cb", "rcb3"],
    ["lwb", "lcmf", "rcmf", "rwb"],
    ["ss", "cf"],
  ],
  "4-1-3-2": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["dmf"],
    ["lamf", "amf", "ramf"],
    ["ss", "cf"],
  ],
  "4-3-2": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["lcmf3", "dmf", "rcmf3"],
    ["ss", "cf"],
  ],
  "3-4-2-1": [
    ["gk"],
    ["lcb3", "cb", "rcb3"],
    ["lwb", "lcmf", "rcmf", "rwb"],
    ["amf", "amf"],
    ["cf"],
  ],
  "4-4-0" : [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["lwb", "lcmf", "rcmf", "rwb"],
  ],
  "4-3-1" : [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["lcmf3", "dmf", "rcmf3"],
    ["cf"],
  ],
  "4-3-2-1":[
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["lcmf3", "dmf", "rcmf3"],
    ["amf", "amf"],
    ["cf"],
  ],
  "4-3-1-1": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["lcmf3", "dmf", "rcmf3"],
    ["amf"],
    ["cf"],
  ],
  "3-4-1": [
    ["gk"],
    ["lcb3", "cb", "rcb3"],
    ["lwb", "lcmf", "rcmf", "rwb"],
    ["cf"],
  ],
  "3-3-3-1": [
    ["gk"],
    ["lcb3", "cb", "rcb3"],
    ["lcmf3", "dmf", "rcmf3"],
    ["lamf", "amf", "ramf"],
    ["cf"],
  ],
  "4-2-1-2":[
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["ldmf", "rdmf"],
    ["amf"],
    ["ss", "cf"],
  ],
  "4-1-3-1":[
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["dmf"],
    ["lamf", "amf", "ramf"],
    ["cf"],
  ],
  "4-2-2-1":[
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["ldmf", "rdmf"],
    ["amf", "amf"],
    ["cf"],
  ],
  "3-5-1-1":[
    ["gk"],
    ["lcb3", "cb", "rcb3"],
    ["lwb", "lcmf3", "dmf", "rcmf3", "rwb"],
    ["amf"],
    ["cf"],
  ],
  "3-5-1": [
    ["gk"],
    ["lcb3", "cb", "rcb3"],
    ["lwb", "lcmf3", "dmf", "rcmf3", "rwb"],
    ["cf"],
  ],
  "3-4-1-1": [
    ["gk"],
    ["lcb3", "cb", "rcb3"],
    ["lwb", "lcmf", "rcmf", "rwb"],
    ["amf"],
    ["cf"],
  ],
  "5-3-1": [
    ["gk"],
    ["lb5", "lcb3", "cb", "rcb3", "rb5"],
    ["lcmf3", "dmf", "rcmf3"],
    ["cf"],
  ],
  "3-2-3-2": [
    ["gk"],
    ["lcb3", "cb", "rcb3"],
    ["ldmf", "rdmf"],
    ["lamf", "amf", "ramf"],
    ["ss", "cf"],
  ],
  "4-5-1": [
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["lwb", "lcmf3", "dmf", "rcmf3", "rwb"],
    ["cf"],
  ],
  "4-2-2-0":[
    ["gk"],
    ["lb", "lcb", "rcb", "rb"],
    ["ldmf", "rdmf"],
    ["amf", "amf"],
  ]
};
