export const LINK_SENTENCES = {
  OFFENSIF: [
    ["goals", "goalConversion"],
    ["cleanSheets"],
    ["shots", "shotsRatio", "shotsOnPost"],
    ["shotOutsideBox", "shotsOutsideConfidence"],
    ["shotFromBox", "shotFromDangerZone"],
    ["headShotsRatio", "headShotsOnTarget"],
  ],
  DEFENSIF: [
    ["goals", "cleanSheets"],
    ["shots", "headShotRatio"],
    ["crossesTotal", "crossesSuccessful"],
    ["shotBlocked", "crossesBlocked"],
    ["shotsfromBox", "shotsfromDangerZone"],
    ["counterAttacks"],
    ["opponentOffsides"],
    ["gkSaves"],
  ],
  DISTRIBUTION: [
    ["passes", "passesRatio"],
    ["assists"],
    ["keyPasses", "shotAssists"],
    ["smartPasses", "throughPasses", "smartPassesRatio", "throughPassesRatio"],
    ["crosses", "crossesRatio"],
    ["longPassesRatio"],
    ["passToPenaltyAreas", "deepCompletedPasses"],
  ],
  PERCUSSION: [
    ["dribbles", "dribblesRatio"],
    ["progressiveRunRatio"],
    ["progressivePasses", "progressivePassesRatio"],
  ],
  RECOVERY: [
    ["losses", "lossesRatioField"],
    ["interceptions", "interceptionsOpponent"],
    ["recoveries", "recoveriesRatioField"],
    ["duels", "duelsRatio"],
    ["defensiveDuelsRatio"],
    ["offensiveDuelsRatio"],
    ["aerialDuelsRatio"],
    ["slidingTacklesRatio"],
    ["groundDuelsRatio"],
    ["looseBallDuelsRatio"],
    ["dribblesAgainstRatio"],
    ["opponentOffsides"],
  ],
  PRESSING: [],
  FREEKICKS: [
    ["cornersRatio"],
    ["freeKicksRatio"],
    ["directFreeKicksRatio"],
    ["freeKicksWithShotRatio"],
  ],
  POSSESSION: [["groupPossession"], ["groupOpponentPossession"]],
};
