export const LINK_SENTENCES = {
  OFFENSIF: {
    Goals: ["goals", "goalsEfficiency"],
    GoalsMean: ["goalMean"],
    cleanSheets: ["cleanSheets"],
    Shots: ["shots", "shotsRatio"],
    shotsOutsideConfidence: ["shotOutsideBox", "shotsOutsideConfidence"],
    headShotsRatio: ["headShotsRatio", "headShotsOnTarget"],
    withShots: ["withShots"],
    counterAttacks: ["counterAttacks"],
    Offsides: ["Offsides"],
  },
  DEFENSIF: {
    goals2: ["goals2", "cleanSheets2"],
    goalMean2: ["goalMean2"],
    attacks: ["attacks", "withShots2"],
    shots2: ["shots2", "shotsFromBox2"],
    shotBlocked2: ["shotBlocked2", "headShotsRatio2"],
    crossesTotal2: ["crossesTotal2", "crossesSuccessful2"],
    crossesBlocked2: ["crossesBlocked2"],
    counterAttacks2: ["counterAttacks2"],
    corners2: ["corners2", "cornersRatio2"],
    freeKicksWithShot2: ["freeKicksWithShot2", "freeKicksWithShotRatio2"],
    opponentOffsides2: ["opponentOffsides2"],
    gkSaves2: ["gkSaves2"],
  },
  DISTRIBUTION: {
    passes: ["passes", "passesRatio"],
    shortLongRatio: ["shortLongRatio", "longPassesRatio"],
    keyPasses: ["keyPasses"],
    keyPassesRatio: ["keyPassesRatio"],
    smartPasses: ["smartPasses"],
    smartPassesRatio: ["smartPassesRatio"],
    crosses: ["crosses", "crossesRatio"],
    throughPasses: ["throughPasses"],
    throughPassesRatio: ["throughPassesRatio"],
    passToFinalThirds: ["passToFinalThirds", "passToFinalThirdsRatio"],
    passToPenaltyAreas: ["passToPenaltyAreas"],
    passToPenaltyAreasRatio: ["passToPenaltyAreasRatio"],
    assists: ["assists"],
  },
  PERCUSSION: {
    dribbles: ["dribbles", "dribblesRatio"],
    progressiveRun: ["progressiveRun"],
    progressivePasses: ["progressivePasses"],
    progressivePassesRatio: ["progressivePassesRatio"],
  },
  RECOVERY: {
    losses: ["losses"],
    interceptions: ["interceptions"],
    interceptionsOpponent: ["interceptionsOpponent"],
    recoveries: ["recoveries"],
    duels: ["duels", "duelsRatio"],
    defensiveDuelsRatio: ["defensiveDuelsRatio", "dribblesSuccessful"],
    aerialDuelsRatio: ["aerialDuelsRatio"],
    slidingTacklesRatio: ["slidingTacklesRatio"],
    groundDuelsRatio: ["groundDuelsRatio"],
    looseBallDuelsRatio: ["looseBallDuelsRatio"],
  },
  FREEKICKS: {
    cornersRatio: ["cornersRatio"],
    freekicksRatio: ["freekicksRatio"],
    directFreeKicksRatio: ["directFreeKicksRatio"],
    freeKicksWithShotRatio: ["freeKicksWithShotRatio"],
  },
  PRESSING: {
    ppda: ["ppda"],
    challengeIntensity: ["challengeIntensity"],
  },
  POSSESSION: {
    // groupPossession: ["groupPossession"],
    // groupOpponentPossession: ["groupOpponentPossession"],
  },
};
