//link tpi
export const LINK_SENTENCES = {
  OFFENSIF: {
    Goals: ["goals", "goalsEfficiency"],
    GoalsMean: ["goalMean"],
    cleanSheets: ["cleanSheets"],
    Shots: ["groupShotsRatio.shots", "groupShotsRatio.shotsRatio"],
    shotsOutsideConfidence: [
      "groupShotDistance.shotOutsideBox",
      "groupShotDistance.shotsOutsideConfidence",
    ],
    headShotsRatio: [
      "groupHeadShots.headShotsRatio",
      "groupHeadShots.headShotsOnTarget",
    ],
    withShots: ["withShots"],
    counterAttacks: ["counterAttacks"],
    Offsides: ["Offsides"],
  },
  DEFENSIF: {
    goals2: ["goals2", "cleanSheets2"],
    goalMean2: ["goalMean2"],
    groupPasses: ["groupPasses"],
    attacks: ["groupAttacks.attacks", "groupAttacks.withShots2"],
    shots2: ["shots2", "groupShotDistance2.shotsFromBox2"],
    shotBlocked2: [
      "groupOpportunityBlocked.shotBlocked2",
      "groupHeadShot2.headShotsRatio2",
    ],
    crossesTotal2: [
      "groupOpportunityBlocked.crossesTotal2",
      "groupOpportunityBlocked.crossesSuccessful2",
    ],
    crossesBlocked2: ["groupOpportunityBlocked.crossesBlocked2"],
    counterAttacks2: ["counterAttacks2"],
    corners2: ["groupFreeKicks.corners2", "groupFreeKicks.cornersRatio2"],
    freeKicksWithShot2: [
      "groupFreeKicks.freeKicksWithShot2",
      "groupFreeKicks.freeKicksWithShotRatio2",
    ],
    opponentOffsides2: ["opponentOffsides2"],
    gkSaves2: ["gkSaves2"],
  },
  DISTRIBUTION: {
    passes: ["passes", "passesRatio"],
    shortLongRatio: [
      "groupPassesDistances.shortLongRatio",
      "groupPassesDistances.longPassesRatio",
    ],
    keyPasses: ["groupkeyPasses.keyPasses"],
    keyPassesRatio: ["groupkeyPasses.keyPassesRatio"],
    smartPasses: ["groupSmartPasses.smartPasses"],
    smartPassesRatio: ["groupSmartPasses.smartPassesRatio"],
    crosses: ["groupCrosses.crosses", "groupCrosses.crossesRatio"],
    throughPasses: ["groupThroughPasses.throughPasses"],
    throughPassesRatio: ["groupThroughPasses.throughPassesRatio"],
    passToFinalThirds: [
      "groupPassToFinalThirds.passToFinalThirds",
      "groupPassToFinalThirds.passToFinalThirdsRatio",
    ],
    passToPenaltyAreas: ["groupPassesZone.passToPenaltyAreas"],
    "groupPassesZone.passToPenaltyAreasRatio": [
      "groupPassesZone.passToPenaltyAreasRatio",
    ],
    assists: ["assists"],
  },
  PERCUSSION: {
    dribbles: ["groupDribbles.dribbles", "groupDribbles.dribblesRatio"],
    progressiveRun: ["progressiveRun"],
    progressivePasses: ["groupProgessivePasses.progressivePasses"],
    progressivePassesRatio: ["groupProgessivePasses.progressivePassesRatio"],
  },
  RECOVERY: {
    losses: ["losses"],
    interceptions: ["interceptions"],
    interceptionsOpponent: ["interceptionsOpponent"],
    recoveries: ["recoveries"],
    duels: ["groupDuels.duels", "groupDuels.duelsRatio"],
    defensiveDuels: ["groupDefensiveDuels.defensiveDuelsRatio"],
    offensiveDuels: ["groupOffensiveDuels.offensiveDuelsRatio"],
    aerialDuels: ["groupAerialDuels.aerialDuelsRatio"],
    slidingTacklesRatio: ["groupSlidingTackles.slidingTacklesRatio"],
    groundDuels: ["groupGroundDuels.groundDuelsRatio"],
    looseBallDuels: ["grouplooseBallDuels.looseBallDuelsRatio"],
    dribblesSuccessful: ["groupDribblesAgainst.dribblesSuccessful"],
    fouls: ["fouls"],
  },
  FREEKICKS: {
    cornersRatio: ["cornersRatio"],
    freekicksRatio: ["freekicksRatio"],
    directFreeKicksRatio: ["directFreeKicksRatio"],
    freeKicksWithShotRatio: ["freeKicksWithShotRatio"],
  },
  PRESSING: {
    ppda: ["groupPressing.ppda"],
    challengeIntensity: ["groupPressing.challengeIntensity"],
  },
  POSSESSION: {
    groupPossession: ["groupPossession"],
    groupOpponentPossession: ["groupOpponentPossession"],
  },
};
