export const PPI_CATEGORY_LABEL: any = {
  CREATION: "CREATION",
  DISTRIBUTION: "DISTRIBUTION",
  DUELS: "DUELS",
  FINITION: "FINITION",
  GOALKEEPER: "GOALKEEPER",
  PERCUSSION: "PERCUSSION",
  POSSESSION: "POSSESSION",
  SET_PIECES: "SET_PIECES",
};
