export const TPI_CATEGORY_LABEL: any = {
  OFFENSIF: "OFFENSIVE",
  DEFENSIF: "DEFENSIVE",
  DISTRIBUTION: "DISTRIBUTION",
  PERCUSSION: "PERCUSSION",
  RECOVERY: "RECOVERY",
  PRESSING: "PRESSING",
  FREEKICKS: "FREEKICKS",
  POSSESSION: "GAME_SET",
};

export const TPI_ORDER_CHART: any = {
  OFFENSIF: "OFFENSIVE",
  DEFENSIF: "DEFENSIVE",
  DISTRIBUTION: "DISTRIBUTION",
  PERCUSSION: "PERCUSSION",
  RECOVERY: "RECOVERY",
  PRESSING: "PRESSING",
  FREEKICKS: "FREEKICKS",
  POSSESSION: "GAME_SET",
};

export const TPI_SUMMARY: any = {
  OFFENSIF: [
    "L’ équipe présente des statistiques offensives très intéressantes par rapport à celles de ses adversaires.",
    "L’ équipe présente des statistiques offensives intéressantes par rapport à celles de ses adversaires.",
    "L’ équipe présente des statistiques offensives juste acceptables par rapport à celles de ses adversaires.",
    "L’ équipe présente des statistiques offensives assez faibles par rapport à celles de ses adversaires.",
    "L’ équipe présente des statistiques offensives faibles par rapport à celles de ses adversaires.",
    "L’ équipe présente des statistiques offensives trop faibles par rapport à celles de ses adversaires.",
  ],
  goals: [
    "Le nombre de buts inscrit est très élevé",
    "Le nombre de buts inscrit est élevé",
    "Le nombre de buts inscrit est assez élevé",
    "Le nombre de buts inscrit n'est pas suffisamment élevé",
    "Le nombre de buts inscrit est insuffisant",
    "Le nombre de buts inscrit est très insuffisant",
  ],
  goalsEfficiency: [
    "le ratio d'efficacité est excellent.",
    "le ratio d'efficacité est satisfaisant.",
    "le ratio d'efficacité est acceptable.",
    "le ratio d'efficacité n'est pas assez satisfaisant.",
    "le ratio d'efficacité n'est pas satisfaisant.",
    "le ratio d'efficacité n'est pas du tout satisfaisant.",
  ],
  goalMean: [
    "La régularité offensive est une grande force de l'équipe.",
    "La régularité offensive est une force de l'équipe.",
    "Offensivement l'équipe est moyennement régulière.",
    "Offensivement l'équipe n'est pas assez régulière.",
    "L' irrégularité offensive est une faiblesse importante de l'équipe.",
    "L' irrégularité offensive est une grande faiblesse de l'équipe.",
  ],
  cleanSheets: [
    "Elle comptabilise très peu de matchs sans marquer.",
    "Elle comptabilise peu de matchs sans marquer.",
    "Elle comptabilise assez peu de matchs sans marquer.",
    "Elle comptabilise un peu trop de matchs sans marquer.",
    "Elle comptabilise trop de matchs sans marquer.",
    "Elle comptabilise beaucoup trop de matchs sans marquer.",
  ],
  withShots: [
    "Un très grand nombre d'actions se terminent par des tirs.",
    "Un grand nombre d'actions se terminent par des tirs.",
    "Un nombre acceptable d'actions se terminent pas des tirs.",
    "Un assez petit nombre d'actions se terminent pas des tirs.",
    "Un petit nombre d'actions se terminent pas des tirs.",
    "Un très petit nombre d'actions se terminent pas des tirs.",
  ],
  "groupShots.shots": [
    "L' équipe à énormément de tirs à son compteur",
    "L' équipe à beaucoup de tirs à son compteur",
    "L' équipe à suffisamment de tirs à son compteur",
    "L' équipe n'a pas suffisamment de tirs à son compteur",
    "L' équipe à peu de tirs à son compteur",
    "L' équipe à très peu de tirs à son compteur",
  ],
  "groupShots.shotsRatio": [
    "une précision très favorable.",
    "une précision favorable.",
    "une précision acceptable.",
    "une précision assez défavorable.",
    "une précision défavorable.",
    "une précision extrêmement défavorable.",
  ],
  "groupShotDistance.shotOutsideBox": [
    "Les tirs de l’extérieur de la surface sont très nombreux,",
    "Les tirs de l’extérieur de la surface sont nombreux,",
    "Les tirs de l’extérieur de la surface sont assez nombreux,",
    "Les tirs de l’extérieur de la surface sont assez rares,",
    "Les tirs de l’extérieur de la surface sont rares,",
    "Les tirs de l’extérieur de la surface sont très rares,",
  ],
  "groupShotDistance.shotsOutsideConfidence": [
    "le taux de réussite vraiment bénéfique.",
    "le taux de réussite bénéfique.",
    "le taux de réussite moyennement bénéfique.",
    "le taux de réussite pas assez bénéfique.",
    "le taux de réussite vraiment pénalisant.",
    "le taux de réussite extrêmement pénalisant.",
  ],
  shotFromBox: [
    "L’ équipe a énormément d'aisance tactique et technique pour se mettre dans les meilleures dispositions de frappes.",
    "L’ équipe a beaucoup d'aisance tactique et technique pour se mettre dans les meilleures dispositions de frappes.",
    "L’ équipe a suffisamment d'aisance tactique et technique pour se mettre dans les meilleures dispositions de frappes.",
    "L’ équipe n'a pas suffisamment d'aisance tactique et technique pour se mettre dans les meilleures dispositions de frappes.",
    "L’ équipe a trop de déficience tactique et technique pour se mettre dans les meilleures dispositions de frappes.",
    "L’ équipe éprouve beaucoup trop de déficience tactique et technique pour se mettre dans les meilleures dispositions de frappes.",
  ],
  "groupHeadShots.headShotsRatio": [
    "Le jeu de têtes est très régulièrement utilisé",
    "Le jeu de têtes est régulièrement utilisé",
    "Le jeu de têtes est moyennement utilisé",
    "Le jeu de têtes est assez rarement utilisé",
    "Le jeu de têtes est rarement utilisé",
    "Le jeu de têtes est très rarement utilisé",
  ],
  "groupHeadShots.headShotsOnTarget": [
    "elles sont très souvent efficaces.",
    "elles sont souvent efficaces.",
    "elles sont tout juste efficaces.",
    "elles ne sont pas assez efficaces.",
    "elles ne sont pas efficaces.",
    "elles ne sont absolument pas efficaces.",
  ],
  Offsides: [
    "Les joueurs sont très rarement en position de hors-jeu.",
    "Les joueurs sont rarement en position de hors-jeu.",
    "Les joueurs sont assez rarement en position de hors-jeu.",
    "Les joueurs sont assez régulièrement en position de hors-jeu.",
    "Les joueurs sont régulièrement en position de hors-jeu.",
    "Les joueurs sont très régulièrement en position de hors-jeu.",
  ],
  counterAttacks: [
    "L'équipe surprend très souvent ses adversaires en contre-attaque.",
    "L'équipe surprend souvent ses adversaires en contre-attaque.",
    "L'équipe surprend assez souvent ses adversaires en contre-attaque.",
    "L'équipe surprend assez peu ses adversaires en contre-attaque.",
    "L'équipe surprend peu ses adversaires en contre-attaque.",
    "L'équipe surprend très peu ses adversaires en contre-attaque.",
  ],
  DEFENSIF: [
    "Les statistiques défensives sont très favorables et mettent en évidence la grande solidité du bloc équipe.",
    "Les statistiques défensives sont favorables et mettent en évidence la solidité du bloc équipe.",
    "Les statistiques défensives sont justes favorables et mettent en évidence une certaine solidité du bloc équipe.",
    "Les statistiques défensives sont assez défavorables et mettent en évidence une certaine fragilité du bloc équipe.",
    "Les statistiques défensives sont défavorables et mettent en évidence la fragilité du bloc équipe.",
    "Les statistiques défensives sont très défavorables et mettent en évidence la fragilité du bloc équipe.",
  ],
  goals2: [
    "L‘ équipe encaisse très peu de buts",
    "L‘ équipe encaisse peu de buts",
    "L‘ équipe encaisse un peu trop de buts",
    "L‘ équipe encaisse beaucoup de buts",
    "L‘ équipe encaisse beaucoup trop de buts",
    "L‘ équipe encaisse énormément de buts",
  ],
  goalMean2: [
    "La régularité défensive est une grande force de l'équipe.",
    "La régularité défensive est une force de l'équipe.",
    "Défensivement l'équipe est moyennement régulière.",
    "Défensivement l'équipe n'est pas assez régulière.",
    "L' irrégularité défensive est une faiblesse importante de l'équipe.",
    "L' irrégularité défensive est une faiblesse trop importante de l'équipe.",
  ],
  cleanSheets2: [
    "son total de clean sheets est très avantageux.",
    "son total de clean sheets est avantageux.",
    "son total de clean sheets est acceptable.",
    "son total de clean sheets n'est pas assez favorable.",
    "son total de clean sheets est pénalisant.",
    "son total de clean sheets est trop pénalisant.",
  ],
  "groupHeadShot2.headShotsRatio2": [
    "une très forte proportion de ces tirs sont des têtes.",
    "une forte proportion de ces tirs sont des têtes.",
    "une petite proportion de ces tirs sont des têtes.",
    "une assez faible proportion de ces tirs sont des têtes.",
    "une faible proportion de ces tirs sont des têtes.",
    "une très faible proportion de ces tirs sont des têtes.",
  ],
  "groupShotDistance2.shotsFromBox2": [
    "les joueurs adverses se retrouvent très rarement dans des positions dangereuses.",
    "les joueurs adverses se retrouvent rarement dans des positions dangereuses.",
    "les joueurs adverses se retrouvent un peu trop souvent dans des positions dangereuses.",
    "les joueurs adverses se retrouvent assez souvent dans des positions dangereuses.",
    "les joueurs adverses se retrouvent trop souvent dans des positions dangereuses.",
    "les joueurs adverses se retrouvent beaucoup trop souvent dans des positions dangereuses.",
  ],
  "groupOpportunityBlocked.crossesTotal2": [
    "En ce qui concerne les centres, l'équipe en subit très peu",
    "En ce qui concerne les centres, l'équipe en subit peu",
    "En ce qui concerne les centres, l'équipe en subit moyennement",
    "En ce qui concerne les centres, l'équipe en subit un peu trop",
    "En ce qui concerne les centres, l'équipe en subit beaucoup",
    "En ce qui concerne les centres, l'équipe en subit énormément",
  ],
  "groupOpportunityBlocked.crossesSuccessful2": [
    "ils sont très peu dangereux pour l'arrière-garde.",
    "ils sont peu dangereux pour l'arrière-garde.",
    "ils sont assez peu dangereux pour l'arrière-garde.",
    "ils sont assez dangereux pour l'arrière-garde.",
    "ils sont souvent dangereux pour l'arrière-garde.",
    "ils sont très souvent dangereux pour l'arrière-garde.",
  ],
  "groupOpportunityBlocked.crossesBlocked2": [
    "En proportion le nombre de centres intercepté est très favorable et met en évidence un manque important de repli des latéraux.",
    "En proportion le nombre de centres intercepté est favorable et met en évidence un manque important de repli des latéraux.",
    "En proportion le nombre de centres intercepté est juste acceptable et met en évidence un manque important de repli des latéraux.",
    "En proportion le nombre de centres intercepté est assez faible et met en évidence un manque important de repli des latéraux.",
    "En proportion le nombre de centres intercepté est faible et met en évidence un manque important de repli des latéraux.",
    "En proportion le nombre de centres intercepté est trop faible et met en évidence un manque important de repli des latéraux.",
  ],
  counterAttacks2: [
    "À noter également que l’équipe se fait très rarement surprendre en contre-attaques.",
    "À noter également que l’équipe se fait rarement surprendre en contre-attaques.",
    "À noter également que l’équipe se fait peu surprendre en contre-attaques.",
    "À noter également que l’équipe se fait un peu trop surprendre en contre-attaques.",
    "À noter également que l’équipe se fait trop surprendre en contre-attaques.",
    "À noter également que l’équipe se fait beaucoup trop, surprendre en contre-attaque.",
  ],
  "groupOpportunityBlocked.shotBlocked2": [
    "Heureusement un nombre très favorable de tirs sont bloqués par les défenseurs.",
    "Heureusement un nombre favorable de tirs sont bloqués par les défenseurs.",
    "Heureusement un nombre acceptable de tirs sont bloqués par les défenseurs.",
    "Malheureusement un nombre assez faible de tirs sont bloqués par les défenseurs.",
    "Malheureusement un nombre trop faible de tirs sont bloqués par les défenseurs.",
    "Malheureusement un nombre beaucoup trop faible de tirs sont bloqués par les défenseurs.",
  ],
  opponentOffsides2: [
    "L' alignement défensif est très performant, car les joueurs adverses sont très souvent pris au piège du hors-jeu.",
    "L' alignement défensif est performant, car les joueurs adverses sont souvent pris au piège du hors-jeu.",
    "L' alignement défensif est moyennement performant, car les joueurs adverses sont quelques fois pris au piège du hors-jeu.",
    "L' alignement défensif n'est pas assez performant, car les joueurs adverses ne sont pas suffisamment pris au piège du hors-jeu.",
    "L' alignement défensif n'est pas performant, car les joueurs adverses sont souvent pris au piège du hors-jeu.",
    "L' alignement défensif n'est du tout performant, car les joueurs adverses sont très souvent pris au piège du hors-jeu.",
  ],
  gkSaves2: [
    "Les analyses montrent que le ratio d'efficacité du gardien est très rassurant.",
    "Les analyses montrent que le ratio d'efficacité du gardien est rassurant.",
    "Les analyses montrent que le ratio d'efficacité du gardien est moyennement rassurant.",
    "Les analyses montrent que le ratio d'efficacité du gardien n'est pas assez rassurant.",
    "Les analyses montrent que le ratio d'efficacité du gardien n'est pas rassurant.",
    "Les analyses montrent que le ratio d'efficacité du gardien n'est pas très rassurant.",
  ],
  "groupAttacks.attacks": [
    "L' équipe subit de très rares offensives",
    "L' équipe subit de rares offensives",
    "L' équipe subit quelques offensives",
    "L' équipe subit un peu trop d'offensives",
    "L' équipe subit trop d'offensives",
    "L' équipe subit beaucoup trop d'offensives",
  ],
  "groupAttacks.withShots2": [
    "une grande majorité d'entre elles sont dangereuses.",
    "une majorité d'entre elles sont dangereuses.",
    "seulement une petite majorité d'entre elles sont dangereuses.",
    "seulement une grande minorité d'entre elles sont dangereuses.",
    "seulement une minorité d'entre elles sont dangereuses.",
    "seulement une petite minorité d'entre elles sont dangereuses.",
  ],
  shots2: [
    "En effet la fréquence des frappes est très faible",
    "En effet la fréquence des frappes est faible",
    "En effet la fréquence des frappes est acceptable",
    "En effet la fréquence des frappes est modérée",
    "En effet la fréquence des frappes est importante",
    "En effet la fréquence des frappes est très importante",
  ],
  "groupFreeKicks.corners2": [
    "Les adversaires comptabilisent très peu de corners",
    "Les adversaires comptabilisent peu de corners",
    "Les adversaires comptabilisent quelques corners",
    "Les adversaires comptabilisent trop de corners",
    "Les adversaires comptabilisent beaucoup de corners",
    "Les adversaires comptabilisent énormément de corners",
  ],
  "groupFreeKicks.cornersRatio2": [
    "ils ne représentent qu'un danger très faible pour la défense.",
    "ils ne représentent qu'un danger plutôt faible pour la défense.",
    "ils ne représentent qu'un danger assez faible pour la défense.",
    "ils représentent un réel danger pour la défense.",
    "ils représentent souvent un réel danger pour la défense.",
    "ils représentent très souvent un réel danger pour la défense.",
  ],
  "groupFreeKicks.freeKicksWithShot2": [
    "Ils subissent très peu de coups francs offensifs ",
    "Ils subissent peu de coups francs offensifs",
    "Ils subissent quelques coups francs offensifs",
    "Ils subissent trop de coups francs offensifs",
    "Ils subissent beaucoup de coups francs offensifs",
    "Ils subissent énormément de coups francs offensifs",
  ],
  "groupFreeKicks.freeKicksWithShotRatio2": [
    "heureusement le pourcentage de réussite est très faible.",
    "heureusement le pourcentage de réussite est faible.",
    "heureusement le pourcentage de réussite est assez faible.",
    "malheureusement le pourcentage de réussite n'est pas assez faible.",
    "malheureusement le pourcentage de réussite est élevé.",
    "malheureusement le pourcentage de réussite est très élevé.",
  ],
  groupPasses: [
    "Les espaces sont vraiment rares et empêchent très fortement les adversaires de développer un jeu de passes dangereux.",
    "Les espaces sont rares et empêchent fortement les adversaires de développer un jeu de passes dangereux.",
    "Les espaces ne sont pas assez rares et n'empêchent que moyennement les adversaires de développer un jeu de passes dangereux.",
    "Les espaces sont assez fréquents et n'empêchent pas suffisamment les adversaires de développer un jeu de passes dangereux.",
    "Les espaces sont fréquents et n'empêchent que faiblement les adversaires de développer un jeu de passes dangereux.",
    "Les espaces sont très fréquents et n'empêchent que trop faiblement les adversaires de développer un jeu de passes dangereux.",
  ],
  DISTRIBUTION: [
    "Le volume et la précision des passes apportent à l'équipe une très bonne maitrise.",
    "Le volume et la précision des passes apportent à l'équipe une bonne maitrise.",
    "Le volume et la précision des passes apportent à l'équipe une maitrise du jeu acceptable.",
    "Le volume et la précision des passes n'apportent pas à l'équipe une assez bonne maitrise.",
    "Le volume et la précision des passes n'apportent pas à l'équipe une bonne maitrise.",
    "Le volume et la précision des passes n'apportent pas à l'équipe une très bonne maitrise.",
  ],
  passes: [
    "L'équipe réalise beaucoup plus de passes que ses adversaires",
    "L'équipe réalise plus de passes que ses adversaires",
    "L'équipe réalise un peu plus de passes que ses adversaires",
    "L'équipe réalise un peu moins de passes que ses adversaires",
    "L'équipe réalise moins de passes que ses adversaires",
    "L'équipe réalise beaucoup moins de passes que ses adversaires",
  ],
  passesRatio: [
    "elles sont souvent beaucoup plus précises.",
    "elles sont souvent plus précises.",
    "elles sont moyennement précises.",
    "elles sont un peu moins précises.",
    "elles sont moins précises.",
    "elles sont beaucoup moins précises.",
  ],
  assists: [
    "Le nombre de passes décisives montre une très grande efficacité offensive.",
    "Le nombre de passes décisives montre une grande efficacité offensive.",
    "Le nombre de passes décisives montre une efficacité offensive plutôt modérée.",
    "Le nombre de passes décisives montre une assez faible efficacité offensive.",
    "Le nombre de passes décisives montre une faible efficacité offensive.",
    "Le nombre de passes décisives montre une très faible efficacité offensive.",
  ],
  "groupkeyPasses.keyPasses": [
    "L’équipe se crée un volume d’actions très élevé.",
    "L’équipe se crée un volume d’actions élevé.",
    "L’équipe se crée un volume d’actions légèrement favorable.",
    "L’équipe se crée un volume d’actions assez limité.",
    "L’équipe se crée un nombre d’actions trop limité.",
    "L’équipe se crée un nombre d’actions vraiment trop limité.",
  ],
  "groupkeyPasses.keyPassesRatio": [
    "Et une très grande proportion de ces actions sont transformées en tirs.",
    "Et une grande proportion de ces actions sont transformées en tirs.",
    "Et une proportion trop modérée de ces actions sont transformées en tirs.",
    "Et une petite proportion de ces actions sont transformées en tirs.",
    "Et une très petite proportion de ces actions sont transformées en tirs.",
    "Et seulement une infime proportion de ces actions sont transformées en tirs.",
  ],
  "groupSmartPasses.smartPasses": [
    "Les passes intelligentes et créatives sont omniprésentes dans le jeu de l'équipe.",
    "Les passes intelligentes et créatives sont présentes dans le jeu de l'équipe.",
    "Les passes intelligentes et créatives sont moyennement fréquentes dans le jeu de l'équipe.",
    "Les passes intelligentes et créatives sont assez peu présentes dans le jeu de l'équipe.",
    "Les passes intelligentes et créatives sont peu présentes dans le jeu de l'équipe.",
    "Les passes intelligentes et créatives sont rarissimes dans le jeu de l'équipe.",
  ],
  "groupSmartPasses.smartPassesRatio": [
    "La justesse technique est présente et très favorable.",
    "La justesse technique est présente et favorable.",
    "La justesse technique est acceptable.",
    "Le manque de justesse technique pour ce type de passe est assez pénalisant.",
    "Le manque de justesse technique pour ce type de passe est pénalisant.",
    "Le manque de justesse technique pour ce type de passe est trop pénalisant.",
  ],
  "groupThroughPasses.throughPasses": [
    "Les mouvements dans la profondeur sont de très fréquent.",
    "Les mouvements dans la profondeur sont de fréquent.",
    "Les mouvements dans la profondeur sont moyennement fréquents.",
    "Les mouvements dans la profondeur sont assez rares.",
    "Les mouvements dans la profondeur sont rares.",
    "Les mouvements dans la profondeur sont très rares.",
  ],
  "groupThroughPasses.throughPassesRatio": [
    "Et les joueurs sont très souvent servis avec précision.",
    "Et les joueurs sont souvent servis avec précision.",
    "Et les joueurs sont plutôt servis avec précision.",
    "Et les joueurs sont assez peu servis avec précision.",
    "Et les joueurs sont peu servis avec précision.",
    "Et les joueurs sont très peu servis avec précision.",
  ],
  "groupCrosses.crosses": [
    "L'équipe effectue énormément de centres,",
    "L'équipe effectue beaucoup de centres,",
    "L'équipe effectue quelques centres,",
    "L'équipe effectue assez peu de centres,",
    "L'équipe effectue peu de centres,",
    "L'équipe effectue très peu de centres,",
  ],
  "groupCrosses.crossesRatio": [
    "ils sont très précis et prolifiques.",
    "ils sont précis et prolifiques.",
    "ils ne sont que moyennement précis et prolifiques.",
    "ils sont assez imprécis et donc peu prolifiques.",
    "ils sont souvent imprécis et donc rarement prolifiques.",
    "ils sont trop souvent imprécis donc très rarement prolifiques.",
  ],
  "groupPassToFinalThirds.passToFinalThirds": [
    "Une très bonne proportion des passes sont effectuées dans le tiers offensif",
    "Une bonne proportion de passes sont effectuées dans le tiers offensif",
    "Une légère proportion de passes sont effectuées dans le tiers offensif",
    "Une faible proportion de passes sont effectuées dans le tiers offensif",
    "Une petite proportion de passes sont effectuées dans le tiers offensif",
    "Une très petite proportion de passes sont effectuées dans le tiers offensif",
  ],
  "groupPassToFinalThirds.passToFinalThirdsRatio": [
    "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est très satisfaisant.",
    "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est satisfaisant.",
    "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est acceptable.",
    "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est assez bas.",
    "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est vraiment bas.",
    "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est vraiment trop bas.",
  ],
  "groupPassesDistances.shortLongRatio": [
    "Le jeu long est très souvent utilisé",
    "Le jeu long est souvent utilisé",
    "Le jeu long est moyennement utilisé",
    "Le jeu long est assez peu utilisé",
    "Le jeu long est rarement utilisé",
    "Le jeu long est très rarement utilisé",
  ],
  "groupPassesDistances.longPassesRatio": [
    "le pourcentage de réussite est très bon.",
    "le pourcentage de réussite est bon.",
    "le pourcentage de réussite est juste acceptable.",
    "le pourcentage de réussite n'est pas assez bon.",
    "le pourcentage de réussite n'est pas bon.",
    "le pourcentage de réussite n'est vraiment pas bon.",
  ],
  "groupPassesZone.passToPenaltyAreas": [
    "Il y a énormément de passes qui sont reçues dans la surface de réparation adverse.",
    "Il y a beaucoup de passes qui sont reçues dans la surface de réparation adverse.",
    "Seulement quelques passes sont reçues dans la surface de réparation adverse.",
    "Il n'y a pas assez de passes qui sont reçues dans la surface de réparation adverse.",
    "Il y a peu de passes qui sont reçues dans la surface de réparation adverse.",
    "Il y a très peu de passes qui sont reçues dans la surface de réparation adverse.",
  ],
  "groupPassesZone.passToPenaltyAreasRatio": [
    "Le niveau de précision est très favorable.",
    "Le niveau de précision est favorable.",
    "Le niveau de précision est légèrement favorable.",
    "Le niveau de précision n'est pas assez favorable.",
    "Le niveau de précision est peu favorable.",
    "Le niveau de précision est très peu favorable.",
  ],
  PERCUSSION: [
    "L'équipe a un jeu de percussion très dangereux pour les adversaires.",
    "L'équipe a un jeu de percussion dangereux pour les adversaires.",
    "L'équipe a un jeu de percussion moyennement dangereux pour les adversaires.",
    "L'équipe n'a pas de jeu de percussion assez dangereux pour les adversaires.",
    "L'équipe n'a pas de jeu de percussion dangereux pour les adversaires.",
    "L'équipe n'a pas du tout de jeu de percussion dangereux pour les adversaires.",
  ],
  "groupDribbles.dribbles": [
    "Les tentatives de dribbles sont très nombreuses",
    "Les tentatives de dribbles sont nombreuses",
    "Les tentatives de dribbles sont juste assez nombreuses",
    "Les tentatives de dribbles ne sont pas assez nombreuses",
    "Les tentatives de dribbles ne sont pas nombreuses",
    "Les tentatives de dribbles ne sont pas très nombreuses",
  ],
  "groupDribbles.dribblesRatio": [
    "le taux de réussite de ces dernières est très favorable.",
    "le taux de réussite de ces dernières est favorable.",
    "le taux de réussite de ces dernières est acceptable.",
    "le taux de réussite de ces dernières n'est pas suffisamment favorable.",
    "le taux de réussite de ces dernières est défavorable.",
    "le taux de réussite de ces dernières est défavorable.",
  ],
  progressiveRun: [
    "Les courses vers le but adverse sont très largement répétées.",
    "Les courses vers le but adverse sont largement répétées.",
    "Les courses vers le but adverse sont moyennement répétées.",
    "Les courses vers le but adverse ne sont pas suffisamment répétées.",
    "Les courses vers le but adverse sont rarement répétées.",
    "Les courses vers le but adverse sont très rarement répétées.",
  ],
  "groupProgessivePasses.progressivePasses": [
    "La proportion des passes réalisées dans la course des joueurs est très élevée.",
    "La proportion des passes réalisées dans la course des joueurs est élevée.",
    "La proportion des passes réalisées dans la course des joueurs est juste acceptable.",
    "La proportion des passes réalisées dans la course des joueurs n’est pas assez élevée.",
    "La proportion des passes réalisées dans la course des joueurs est trop faible.",
    "La proportion des passes réalisées dans la course des joueurs est beaucoup trop faible.",
  ],
  "groupProgessivePasses.progressivePassesRatio": [
    "Elles sont très souvent données dans le bon tempo.",
    "Elles sont souvent données dans le bon tempo.",
    "Elles ne sont que moyennement données dans le bon tempo.",
    "Elles ne sont pas suffisamment données dans le bon tempo.",
    "Elles sont rarement données dans le bon tempo.",
    "Elles sont très rarement données dans le bon tempo.",
  ],
  RECOVERY: [
    "Le niveau de rigueur dans les duels, la récupération et le placement est très élevé.",
    "Le niveau de rigueur dans les duels, la récupération et le placement est élevé.",
    "Le niveau de rigueur dans les duels, la récupération et le placement est juste acceptable.",
    "Le niveau de rigueur dans les duels, la récupération et le placement n'est pas suffisamment élevé.",
    "Le niveau de rigueur dans les duels, la récupération et le placement est trop faible.",
    "Le niveau de rigueur dans les duels, la récupération et le placement est beaucoup trop faible.",
  ],
  losses: [
    "Les joueurs perdent beaucoup moins de ballons que leurs concurrents.",
    "Les joueurs perdent moins de ballons que leurs concurrents.",
    "Les joueurs perdent un peu moins de ballons que leurs concurrents.",
    "Les joueurs perdent un peu plus de ballons que leurs concurrents.",
    "Les joueurs perdent plus de ballons que leurs concurrents.",
    "Les joueurs perdent beaucoup plus de ballons que leurs concurrents.",
  ],
  interceptions: [
    "Le taux d’interceptions est très élevé et révèle un certain sens du placement et de l'anticipation.",
    "Le taux d’interceptions est élevé et révèle un certain sens du placement et de l'anticipation.",
    "Le taux d’interceptions est acceptable et révèle un certain sens du placement et de l'anticipation.",
    "Le taux d’interceptions est assez faible révèle un certain manque dans le placement et de l'anticipation.",
    "Le taux d’interceptions est faible et révèle un certain manque dans le placement et de l'anticipation.",
    "Le taux d’interceptions est très faible et révèle un certain manque dans le placement et de l'anticipation.",
  ],
  interceptionsOpponent: [
    "Les passes sont très précises et rendent les interceptions adverses très compliquées.",
    "Les passes sont précises et rendent les interceptions adverses très compliquées.",
    "Les passes sont moyennement précises et rendent les interceptions adverses un peu plus faciles.",
    "Les passes sont un peu trop imprécises et facilitent les interceptions adverses.",
    "Les passes sont trop imprécises et facilitent trop les interceptions adverses.",
    "Les passes sont vraiment imprécises et facilitent beaucoup trop les interceptions adverses.",
  ],
  recoveries: [
    "L’équipe montre une très grande efficacité dans la récupération du ballon.",
    "L’équipe montre une grande efficacité dans la récupération du ballon.",
    "L’équipe montre une efficacité assez modérée dans la récupération du ballon.",
    "L’équipe montre assez peu d'efficacité dans la récupération du ballon.",
    "L’équipe montre peu d'efficacité dans la récupération du ballon.",
    "L’équipe montre très peu d'efficacité dans la récupération du ballon.",
  ],
  "groupDuels.duels": [
    "Les joueurs multiplient très fortement le nombre de duels,",
    "Les joueurs multiplient fortement le nombre de duels,",
    "Les joueurs ne multiplient que modérément le nombre de duels,",
    "Les joueurs ne multiplient pas assez le nombre de duels,",
    "Les joueurs ne multiplient pas beaucoup le nombre de duels,",
    "Les joueurs ne multiplient presque pas le nombre de duels,",
  ],
  "groupDuels.duelsRatio": [
    "dans l'ensemble le niveau de réussite est vraiment favorable. En étant plus précis dans l’analyse, nous identifions les points forts et faibles suivants :",
    "dans l'ensemble le niveau de réussite est favorable.En étant plus précis dans l’analyse, nous identifions les points forts et faibles suivants :",
    "dans l'ensemble le niveau de réussite est assez favorable.En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
    "dans l'ensemble le niveau de réussite n'est pas suffisamment favorable. En étant plus précis dans l’analyse, nous identifions les points forts et faibles suivants :",
    "dans l'ensemble le niveau de réussite est défavorable. En étant plus précis dans l’analyse, nous identifions les points forts et faibles suivants :",
    "dans l'ensemble le niveau de réussite est vraiment défavorable. En étant plus précis dans l’analyse, nous identifions les points forts et faibles suivants :",
  ],
  "groupDefensiveDuels.defensiveDuelsRatio": [
    "- Une très grande majorité des duels défensifs sont gagnés par les joueurs",
    "- Une majorité des duels défensifs sont gagnés par les joueurs",
    "- Une petite majorité des duels défensifs sont gagnés par les joueurs",
    "- Une petite majorité des duels défensifs sont perdus par les joueurs",
    "- Une majorité des duels défensifs sont perdus par les joueurs",
    "- Une grande majorité des duels défensifs sont perdus par les joueurs",
  ],
  "groupOffensiveDuels.offensiveDuelsRatio": [
    "- Une très grande majorité des duels offensifs sont gagnés par les joueurs",
    "- Une majorité des duels offensifs sont gagnés par les joueurs",
    "- Une petite majorité des duels offensifs sont gagnés par les joueurs",
    "- Une petite majorité des duels offensifs sont perdus par les joueurs",
    "- Une majorité des duels offensifs sont perdus par les joueurs",
    "- Une grande majorité des duels offensifs sont perdus par les joueurs",
  ],
  "groupDribblesAgainst.dribblesSuccessful": [
    "les tentatives de dribbles adverses sont très souvent avortées.",
    "les tentatives de dribbles adverses sont souvent avortées.",
    "les tentatives de dribbles adverses ne sont que moyennement avortées.",
    "les tentatives de dribbles adverses ne sont pas assez avortées.",
    "les tentatives de dribbles adverses sont rarement avortées.",
    "les tentatives de dribbles adverses sont très rarement avortées.",
  ],
  "groupAerialDuels.aerialDuelsRatio": [
    "- Le timming dans les duels aériens est excellent.",
    "- Le timming dans les duels aériens est bon.",
    "- Le timming dans les duels aériens est tout juste acceptable.",
    "- Le timming dans les duels aériens n'est pas assez bon.",
    "- Le timming dans les duels aériens est mauvais.",
    "- Le timming dans les duels aériens est très mauvais.",
  ],
  "groupSlidingTackles.slidingTacklesRatio": [
    "- Les tacles glissés sont bien maitrisés.",
    "- Les tacles glissés sont bien maitrisés.",
    "- Les tacles glissés sont trop légèrement maitrisés.",
    "- Les tacles glissés sont assez mal maitrisés.",
    "- Les tacles glissés sont mal maitrisés.",
    "- Les tacles glissés sont très mal maitrisés.",
  ],
  "groupGroundDuels.groundDuelsRatio": [
    "- Les joueurs font preuve d’une très bonne agressivité.",
    "- Les joueurs font preuve d’une bonne agressivité.",
    "- Les joueurs font preuve d’une agressivité juste suffisante.",
    "- Les joueurs ne font pas preuve d’une agressivité suffisante.",
    "- Les joueurs font preuve d’un manque important d'agressivité.",
    "- Les joueurs font preuve d’un manque très important d'agressivité.",
  ],
  "groupLooseBallDuels.groupLooseBallDuels": [
    "- Les joueurs font preuve d'une très bonne réactivité.",
    "- Les joueurs font preuve d'une bonne réactivité.",
    "- Les joueurs font preuve d'une assez bonne réactivité.",
    "- Les joueurs ne font pas preuve d'une réactivité suffisante.",
    "- Les joueurs manquent de réactivité.",
    "- Les joueurs manquent terriblement de réactivité.",
  ],
  FREEKICKS: [
    "Les opportunités sur les phases de jeux arrêtés sont très bien exploitées.",
    "Les opportunités sur les phases de jeux arrêtés sont bien exploitées.",
    "Les opportunités sur les phases de jeux arrêtés sont modérément bien exploitées.",
    "Les opportunités sur les phases de jeux arrêtés ne sont pas assez bien exploitées.",
    "Les opportunités sur les phases de jeux arrêtés sont mal exploitées.",
    "Les opportunités sur les phases de jeux arrêtés sont très mal exploitées.",
  ],
  cornersRatio: [
    "Les corners sont très bien négociés, car un très grand nombre d'entre eux aboutissent à une action dangereuse.",
    "Les corners sont bien négociés, car un nombre important d'entre eux aboutissent à une action dangereuse.",
    "Les corners sont moyennement bien négociés, car un nombre insuffisant d'entre eux aboutissent à une action dangereuse.",
    "Les corners sont assez mal négociés, car un petit nombre d'entre eux aboutissent à une action dangereuse.",
    "Les corners sont mal négociés, car un petit nombre d'entre eux aboutissent à une action dangereuse.",
    "Les corners sont très mal négociés, car un trop petit nombre d'entre eux aboutissent à une action dangereuse.",
  ],
  freekicksRatio: [
    "Les opportunités de marquer sur coup franc indirectes sont très importantes.",
    "Les opportunités de marquer sur coup franc indirectes sont importantes.",
    "Les opportunités de marquer sur coup franc indirectes sont modérées.",
    "Les opportunités de marquer sur coup franc indirectes sont assez faibles.",
    "Les opportunités de marquer sur coup franc indirectes sont très faibles.",
    "Les opportunités de marquer sur coup franc indirectes sont beaucoup trop faibles.",
  ],
  directFreeKicksRatio: [
    "La performance des tireurs représente un danger très sérieux pour le gardien adverse.",
    "La performance des tireurs représente un danger sérieux pour le gardien adverse.",
    "La performance des tireurs représente un danger modéré pour le gardien adverse.",
    "La performance des tireurs ne représente pas un danger assez important pour le gardien adverse.",
    "La performance des tireurs ne représente pas un danger important pour le gardien adverse.",
    "La performance des tireurs ne représente pas un danger très important pour le gardien adverse.",
  ],
  freeKicksWithShotRatio: [
    "Il y a une très grande majorité des tirs qui sont due à des coups francs.",
    "Il y a une grande majorité des tirs qui sont dus à des coups francs.",
    "Il y a une légère majorité des tirs qui sont dus à des coups francs.",
    "Il y a une très petite majorité des tirs qui sont dus à des coups francs.",
    "Il y a une petite majorité des tirs qui sont dus à des coups francs.",
    "Il y a une toute petite majorité des tirs qui sont dus à des coups francs.",
  ],
  PRESSING: [
    "L’équipe réalise un pressing de très haute intensité mettant en évidence un niveau physique et tactique favorable.",
    "L’équipe réalise un pressing de haute intensité mettant en évidence un niveau physique et tactique favorable.",
    "L’équipe réalise un pressing d'intensité modéré mettant en évidence un niveau physique et tactique assez favorable.",
    "L’équipe réalise un pressing d'assez faible intensité mettant en évidence un niveau physique et tactique défavorable.",
    "L’équipe réalise un pressing de faible intensité mettant en évidence un niveau physique et tactique défavorable.",
    "L’équipe réalise un pressing de trop faible intensité mettant en évidence un niveau physique et tactique défavorable.",
  ],
  "groupPressing.ppda": [
    "L'équipe est très pressante et empêche très fortement les transmissions adverses.",
    "L'équipe est pressante et empêche très fortement les transmissions adverses.",
    "L'équipe est moyennement pressante et empêche très fortement les transmissions adverses.",
    "L'équipe n'est pas suffisamment pressante et laisse un peu trop jouer les adversaires.",
    "L'équipe n'est pas pressante et laisse jouer les adversaires.",
    "L'équipe n'est pas du tout pressante et laisse dangereusement les adversaires.",
  ],
  "groupPressing.challengeIntensity": [
    "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est très élevé.",
    "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est élevé.",
    "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est légèrement favorable.",
    "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est assez faible.",
    "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est faible.",
    "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est très faible.",
  ],
  POSSESSION: [
    "Qu’importe le style de jeu de ses adversaires, l’équipe s’adapte et garde un très bon niveau de performance.",
    "Qu’importe le style de jeu de ses adversaires, l’équipe s’adapte et garde un bon niveau de performance.",
    "En fonction du style de jeu de ses adversaires, l’équipe s’adapte moyennement, mais garde niveau de performance acceptable.",
    "En fonction du style de jeu de ses adversaires, l’équipe s’adapte assez difficilement et son niveau de performance s’en ressent.",
    "En fonction du style de jeu de ses adversaires, l’équipe s’adapte difficilement et son niveau de performance s’en ressent.",
    "En fonction du style de jeu de ses adversaires, l’équipe s’adapte très difficilement et son niveau de performance s’en ressent.",
  ],
  groupPossession: [
    "Lorsqu’elle est en possession du ballon et doit faire le jeu, son ratio de productivité est vraiment favorable.",
    "Lorsqu’elle est en possession du ballon et doit faire le jeu, son ratio de productivité est favorable.",
    "Lorsqu’elle est en possession du ballon et doit faire le jeu, son ratio de productivité est légèrement favorable.",
    "Lorsqu’elle est en possession du ballon et doit faire le jeu, son ratio de productivité n’est pas suffisamment favorable.",
    "Lorsqu’elle est en possession du ballon et doit faire le jeu, son ratio de productivité est mauvais.",
    "Lorsqu’elle est en possession du ballon et doit faire le jeu, son ratio de productivité est trop mauvais.",
  ],
  groupOpponentPossession: [
    "Quand elle n’a pas le ballon, elle n’en est pas moins compétitive. Son organisation et jeu sans ballon lui confère une très bonne solidité défensive, mais aussi une redoutable efficacité offensive.",
    "Quand elle n’a pas le ballon, elle n’en est pas moins compétitive. Son organisation et jeu sans ballon lui confère une  bonne solidité défensive, mais aussi une efficacité offensive favorable.",
    "Quand elle n’a pas le ballon, elle reste assez compétitive. Son organisation et jeu sans ballon lui confère une assez bonne solidité défensive, mais aussi une efficacité offensive suffisante.",
    "Quand elle n’a pas le ballon, elle n'est pas suffisamment compétitive. Son organisation et jeu sans ballon lui confère une petite fragilité défensive, mais aussi une efficacité offensive insuffisante.",
    "Quand elle n’a pas le ballon, elle est rarement compétitive. Son organisation et jeu sans ballon lui confère une grande fragilité défensive, mais aussi une efficacité offensive trop faible.",
    "Quand elle n’a pas le ballon, elle est rarement compétitive. Son organisation et jeu sans ballon lui confère une très grande fragilité défensive, mais aussi une efficacité offensive beaucoup trop faible.",
  ],
};

export const TPI: any = {
  OFFENSIF: {
    goals: [
      "Le nombre de buts inscrit est très élevé",
      "Le nombre de buts inscrit est élevé",
      "Le nombre de buts inscrit est suffisament élevé",
      "Le nombre de buts inscrit n'est pas suffisament élevé",
      "Le nombre de buts inscrit est insuffisant",
      "Le nombre de buts inscrit est très insuffisant",
    ],
    goalsEfficiency: [
      "le taux de conversion des frappes en but excellent.",
      "le taux de conversion des frappes en but très satisfaisant.",
      "le taux de conversion des frappes en but juste satisfaisant.",
      "le taux de conversion des frappes en but pas satisfaisant.",
      "le taux de conversion des frappes en but trop faible.",
      "le taux de conversion des frappes en but vraiment trop faible.",
    ],
    goalMean: [
      "La régularité affiché tout au long de la saison est une grande force.",
      "La régularité affiché tout au long de la saison est une force.",
      "La régularité affiché tout au long de la saison est tout juste acceptable.",
      "L' irrégularité affiché tout au long de la saison est trop moyenne.",
      "L' irrégularité affiché tout au long de la saison est une faiblesse.",
      "L' irrégularité affiché tout au long de la saison est une grande faiblesse.",
    ],
    cleanSheets: [
      "Elle comptabilise d'ailleurs très peu de matchs sans marquer.",
      "Elle comptabilise d'ailleurs peu de matchs sans marquer.",
      "Elle comptabilise d'ailleurs assez peu de matchs sans marquer.",
      "Elle comptabilise d'ailleurs un peu trop de matchs sans marquer.",
      "Elle comptabilise d'ailleurs trop de matchs sans marquer.",
      "Elle comptabilise d'ailleurs beaucoup trop de matchs sans marquer.",
    ],
    withShots: [
      "L' analyse montre que la grande majorité des offensives se concluent par des tirs.",
      "L' analyse montre que la majorité des offensives se concluent par des tirs.",
      "L' analyse montre qu'une légère majorité des offensives se concluent par des tirs.",
      "L' analyse montre qu'une légère minorité des offensives se concluent par des tirs.",
      "L' analyse montre qu'une minorité des offensives se concluent par des tirs.",
      "L’ analyse montre qu'une grande minorité des offensives se concluent par des tirs.",
    ],
    shots: [
      "L' équipe totabilise un nombre de tirs très élevé",
      "L' équipe totabilise un nombre de tirs élevé",
      "L' équipe totabilise un nombre de tirs tout juste suffisant",
      "L’ équipe totabilise un nombre de tirs tout juste insuffisant",
      "L' équipe totabilise un nombre de tirs trop faible",
      "L' équipe totabilise un nombre de tirs vraiment trop faible",
    ],
    shotsRatio: [
      "un niveau de précision très favorable.",
      "un niveau de précision favorable.",
      "un niveau de précision à peine favorable.",
      "un niveau de précision à peine défavorable.",
      "un niveau de précision défavorable.",
      "un niveau de précision extrêmement défavorable.",
    ],
    shotOutsideBox: [
      "La proportion des frappes depuis l’extérieur de la surface est très importante,",
      "La proportion des frappes depuis l’extérieur de la surface est importante,",
      "La proportion des frappes depuis l’extérieur de la surface est assez importante,",
      "La proportion des frappes depuis l’extérieur de la surface est assez limitée,",
      "La proportion des frappes depuis l’extérieur de la surface est limitée,",
      "La proportion des frappes depuis l’extérieur de la surface est très limitée,",
    ],
    shotsOutsideConfidence: [
      "le taux de réussite vraiment bénéfique.",
      "le taux de réussite bénéfique.",
      "le taux de réussite assez bénéfique.",
      "le taux de réussite pas assez bénéfique.",
      "le taux de réussite vraiment pénalisant.",
      "le taux de réussite extrêmement pénalisant.",
    ],
    shotFromBox: [
      "L’ équipe a énormément d'aisance tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
      "L’ équipe a beaucoup d'aisance tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
      "L’ équipe a suffisament d'aisance tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
      "L’ équipe n'a pas suffisament d'aisance tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
      "L’ équipe a trop de déficience tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
      "L’ équipe éprouve beaucoup trop de déficience tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
    ],
    headShotsRatio: [
      "Proportionnellement au nombre de tirs, les têtes sont très souvent utilisées",
      "Proportionnellement au nombre de tirs, les têtes sont souvent utilisées",
      "Proportionnellement au nombre de tirs, les têtes sont un peu utilisées",
      "Proportionnellement au nombre de tirs, les têtes sont peu utilisées",
      "Proportionnellement au nombre de tirs, les têtes sont rarement utilisées",
      "Proportionnellement au nombre de tirs, les têtes sont très rarement utilisées",
    ],
    headShotsOnTarget: [
      "elles sont très souvent efficaces.",
      "elles sont souvent efficaces.",
      "elles sont tout juste efficaces.",
      "elles ne sont pas assez efficaces.",
      "elles ne sont pas efficaces.",
      "elles ne sont absolument pas efficaces.",
    ],
    Offsides: [
      "Les joueurs sont très rarement en position de hors-jeu.",
      "Les joueurs sont rarement en position de hors-jeu.",
      "Les joueurs sont assez rarement en position de hors-jeu.",
      "Les joueurs sont assez régulièrement en position de hors-jeu.",
      "Les joueurs sont régulièrement en position de hors-jeu.",
      "Les joueurs sont très régulièrement en position de hors-jeu.",
    ],
    counterAttacks: [
      "Et que l' équipe surprend très souvent ses adversaires en contre-attaques.",
      "Et que l' équipe surprend souvent ses adversaires en contre-attaques.",
      "ET que l' équipe surprend assez souvent ses adversaires en contre-attaques.",
      "Et que l' équipe surprend assez peu ses adversaires en contre-attaques.",
      "Et que l' équipe surprend peu ses adversaires en contre-attaques.",
      "Et que l' équipe surprend très peu ses adversaires en contre-attaques.",
    ],
  },
  DEFENSIF: {
    goals2: [
      "L‘ équipe encaisse très peu de buts",
      "L‘ équipe encaisse peu de buts",
      "L‘ équipe encaisse un peu trop de buts",
      "L‘ équipe encaisse beaucoup de buts",
      "L‘ équipe encaisse beaucoup trop de buts",
      "L‘ équipe encaisse énormément de buts",
    ],
    goalMean2: [
      "La régularité affiché tout au long de la saison est vraiment très positive !",
      "La régularité affiché tout au long de la saison est vraiment positive !",
      "La régularité affiché tout au long de la saison est légèrement positive !",
      "L'irrégularité affiché tout au long de la saison est assez inquiétante !",
      "L'irrégularité affiché tout au long de la saison est vraiment inquiétante !",
      "L'irrégularité affiché tout au long de la saison est vraiment très inquiétante !",
    ],
    cleanSheets2: [
      "son total de clean sheets est très avantageux.",
      "son total de clean sheets est avantageux.",
      "son total de clean sheets est assez favorable.",
      "son total de clean sheets n'est pas assez favorable.",
      "son total de clean sheets est pénalisant.",
      "son total de clean sheets est trop pénalisant.",
    ],
    headShotsRatio2: [
      "une très forte proportion de ces tirs sont des têtes.",
      "une forte proportion de ces tirs sont des têtes.",
      "une petite proportion de ces tirs sont des têtes.",
      "une assez faible proportion de ces tirs sont des têtes.",
      "une faible proportion de ces tirs sont des têtes.",
      "une très faible proportion de ces tirssont des têtes.",
    ],
    shotsFromBox2: [
      "les joueurs adverses se retrouvent très rarement dans des positions dangereuses.",
      "les joueurs adverses se retrouvent rarement dans des positions dangereuses.",
      "les joueurs adverses se retrouvent un peu trop souvent dans des positions dangereuses.",
      "les joueurs adverses se retrouvent assez souvent dans des positions dangereuses.",
      "les joueurs adverses se retrouvent trop souvent dans des positions dangereuses.",
      "les joueurs adverses se retrouvent beaucoup trop souvent dans des positions dangereuses.",
    ],
    crossesTotal2: [
      "En ce qui concerne les centres, l'équipe en subit très peu",
      "En ce qui concerne les centres, l'équipe en subit peu",
      "En ce qui concerne les centres, l'équipe en subit assez peu",
      "En ce qui concerne les centres, l'équipe en subit un peu trop",
      "En ce qui concerne les centres, l'équipe en subit beaucoup",
      "En ce qui concerne les centres, l'équipe en subit énormément",
    ],
    crossesSuccessful2: [
      "ils sont très peu dangereux pour l'arrière-garde.",
      "ils sont peu dangereux pour l'arrière-garde.",
      "ils sont assez peu dangereux pour l'arrière-garde.",
      "ils sont assez dangereux pour l'arrière-garde.",
      "ils sont souvent dangereux pour l'arrière-garde.",
      "ils sont très souvent dangereux pour l'arrière-garde.",
    ],
    crossesBlocked2: [
      "En proportion le nombre de centres intercepté est très favorable et met en évidence un manque important de repli des latéraux.",
      "En proportion le nombre de centres intercepté est favorable et met en évidence un manque important de repli des latéraux.",
      "En proportion le nombre de centres intercepté est légèrement favorable et met en évidence un manque important de repli des latéraux.",
      "En proportion le nombre de centres intercepté est assez faible et met en évidence un manque important de repli des latéraux.",
      "En proportion le nombre de centres intercepté est faible et met en évidence un manque important de repli des latéraux.",
      "En proportion le nombre de centres intercepté est trop faible et met en évidence un manque important de repli des latéraux.",
    ],
    counterAttacks2: [
      "À noter également que l’équipe se fait très rarement surprendre en contre-attaques.",
      "À noter également que l’équipe se fait rarement surprendre en contre-attaques.",
      "À noter également que l’équipe se fait peu surprendre en contre-attaques.",
      "À noter également que l’équipe se fait un peu trop surprendre en contre-attaques.",
      "À noter également que l’équipe se fait trop surprendre en contre-attaques.",
      "À noter également que l’équipe se fait beaucoup trop surprendre en contre-attaques.",
    ],
    shotBlocked2: [
      "Heureusement un nombre très favorable de tirs sont bloqués par les défenseurs.",
      "Heureusement un nombre favorable de tirs sont bloqués par les défenseurs.",
      "Heureusement un nombre assez favorable de tirs sont bloqués par les défenseurs.",
      "Malheureusement un nombre assez faible de tirs sont bloqués par les défenseurs.",
      "Malheureusement un nombre trop faible de tirs sont bloqués par les défenseurs.",
      "Malheureusement un nombre beaucoup trop faible de tirs sont bloqués par les défenseurs.",
    ],
    opponentOffsides2: [
      "L' alignement défensif est très performant, car les joueurs adverses sont très souvent pris au piège du hors-jeu.",
      "L' alignement défensif est performant, car les joueurs adverses sont souvent pris au piège du hors-jeu.",
      "L' alignement défensif est assez performant, car les joueurs adverses sont quelques fois pris au piège du hors-jeu.",
      "L' alignement défensif n'est pas assez performant, car les joueurs adverses ne sont pas suffisamment pris au piège du hors-jeu.",
      "L' alignement défensif n'est pas performant, car les joueurs adverses sont souvent pris au piège du hors-jeu.",
      "L' alignement défensif n'est du tout performant, car les joueurs adverses sont très souvent pris au piège du hors-jeu.",
    ],
    gkSaves2: [
      "Les analyses montrent que le ratio d'éfficacité du gardien est très rassurant.",
      "Les analyses montrent que le ratio d'éfficacité du gardien est rassurant.",
      "Les analyses montrent que le ratio d'éfficacité du gardien est assez rassurant.",
      "Les analyses montrent que le ratio d'éfficacité du gardien n'est pas assez rassurant.",
      "Les analyses montrent que le ratio d'éfficacité du gardien n'est pas rassurant.",
      "Les analyses montrent que le ratio d'éfficacité du gardien n'est pas très rassurant.",
    ],
    attacks: [
      "L' équipe ne subit que de très rares offensives",
      "L' équipe ne subit que de rares offensives",
      "L' équipe ne subit que peu offensives",
      "L' équipe subit un peu trop d'offensives",
      "L' équipe subit trop d'offensives",
      "L' équipe subit beaucoup trop d'offensives",
    ],
    withShots2: [
      "une grande majorité d'entre elles sont dangereuses.",
      "une majorité d'entre elles sont dangereuses.",
      "seulement une petite majorité d'entre elles sont dangereuses.",
      "seulement une grande minorité d'entre elles sont dangereuses.",
      "seulement une minorité d'entre elles sont dangereuses.",
      "seulement une petite minorité d'entre elles sont dangereuses.",
    ],
    shots2: [
      "En effet la fréquence des frappes est très faible",
      "En effet la fréquence des frappes est faible",
      "En effet la fréquence des frappes est faible",
      "En effet la fréquence des frappes est modérée",
      "En effet la fréquence des frappes est importante",
      "En effet la fréquence des frappes est très importante",
    ],
    corners2: [
      "Les adversaires comptabilisent très peu de corners",
      "Les adversaires comptabilisent peu de corners",
      "Les adversaires comptabilisent quelques corners",
      "Les adversaires comptabilisent trop de corners",
      "Les adversaires comptabilisent beaucoup de corners",
      "Les adversaires comptabilisent énormément de corners",
    ],
    cornersRatio2: [
      "ils ne représentent qu'un danger très faible pour la défense.",
      "ils ne représentent qu'un danger plutôt faible pour la défense.",
      "ils ne représentent qu'un danger assez faible pour la défense.",
      "ils représentent un réel danger pour la défense.",
      "ils représentent souvent un réel danger pour la défense.",
      "ils représentent très souvent un réel danger pour la défense.",
    ],
    freeKicksWithShot2: [
      "Ils subissent très peu de coups francs offensifs ",
      "Ils subissent peu de coups francs offensifs",
      "Ils subissent assez peu de coups francs offensifs",
      "Ils subissent trop de coups francs offensifs",
      "Ils subissent beaucoup de coups francs offensifs",
      "Ils subissent énormément de coups francs offensifs",
    ],
    freeKicksWithShotRatio2: [
      "heureusement le pourcentage de réussite est très faible.",
      "heureusement le pourcentage de réussite est faible.",
      "heureusement le pourcentage de réussite est assez faible.",
      "malheureusement le pourcentage de réussite n'est pas assez faible.",
      "malheureusement le pourcentage de réussite est élevé.",
      "malheureusement le pourcentage de réussite est très élevé.",
    ],
    groupPasses: [
      "Les espaces sont vraiment rares et empêchent très fortement les adversaires de développer un jeu de passes dangereux.",
      "Les espaces sont rares et empêchent fortement les adversaires de développer un jeu de passes dangereux.",
      "Les espaces sont assez rares et empêchent suffisamment les adversaires de développer un jeu de passes dangereux.",
      "Les espaces sont assez fréquent et n'empêchent pas suffisamment les adversaires de développer un jeu de passes dangereux.",
      "Les espaces sont fréquent et n'empêchent que faiblement les adversaires de développer un jeu de passes dangereux.",
      "Les espaces sont très fréquent et n'empêchent que trop faiblement les adversaires de développer un jeu de passes dangereux.",
    ],
  },
  DISTRIBUTION: {
    passes: [
      "Globalement l'équipe réalise un nombre de passes beaucoup moins important que ses adversaires",
      "Globalement l'équipe réalise un nombre de passes plus important que ses adversaires",
      "Globalement l'équipe réalise un nombre de passes un peu plus important que ses adversaires",
      "Globalement l'équipe réalise un nombre de passes un peu moins important que ses adversaires",
      "Globalement l'équipe réalise un nombre de passes moins important que ses adversaires",
      "Globalement l'équipe réalise un nombre de passes beaucoup plus important que ses adversaires",
    ],
    passesRatio: [
      "elles sont très souvent mieux ajustées.",
      "elles sont souvent mieux ajustées.",
      "elles sont légèrement mieux ajustées.",
      "elles sont un peu moins ajustées.",
      "elles sont moins ajustées.",
      "elles sont vraiment moins ajustées.",
    ],
    assists: [
      "Le nombre de passes décisives est le reflet de l'importante domination de l'équipe.",
      "Le nombre de passes décisives est le reflet de la domination de l'équipe.",
      "Le nombre de passes décisives est le reflet de la faible domination de l'équipe.",
      "Le nombre de passes décisives est le reflet des quelques difficultés de l'équipe.",
      "Le nombre de passes décisives est le reflet des difficultés de l'équipe.",
      "Le nombre de passes décisives est le reflet des grandes difficultés de l'équipe.",
    ],
    keyPasses: [
      "L’ animation offensive est performante, car l’équipe se crée un volume d’actions très élevé.",
      "L’ animation offensive est performante, car l’équipe se crée un volume d’actions élevé.",
      "L’ animation offensive est assez performante, car l’équipe se crée un volume d’actions suffisament élevé.",
      "L’ animation offensive n'est pas assez performante, car l’équipe se crée un volume d’actions limité.",
      "L’ animation offensive n'est vraiment pas performante, car l’équipe se crée un nombre d’actions trop limité.",
      "L’ animation offensive n'est absolument pas performante, car l’équipe se crée un nombre d’actions vraiment trop limité.",
    ],
    keyPassesRatio: [
      "Et l'efficacité est au rendez-vous car une très grande proportion de ces actions sont transformées en tirs.",
      "Et l'efficacité est au rendez-vous car une grande proportion de ces actions sont transformées en tirs.",
      "Et l'efficacité est limitée car une petite proportion de ces actions sont transformées en tirs.",
      "Et l’efficacité n’est pas au rendez-vous, car seulement une petite proportion de ces actions sont transformées en tirs.",
      "Et l’efficacité n’est pas au rendez-vous, car seulement une très petite proportion de ces actions sont transformées en tirs.",
      "Et l’efficacité n’est pas au rendez-vous, car seulement une infime proportion de ces actions sont transformées en tirs.",
    ],
    smartPasses: [
      "Les passes intélligentes et créatives sont omniprésentes dans le jeu de l'équipe.",
      "Les passes intélligentes et créatives sont présentes dans le jeu de l'équipe.",
      "Les passes intélligentes et créatives sont assez présentes dans le jeu de l'équipe.",
      "Les passes intélligentes et créatives sont assez peu présentes dans le jeu de l'équipe.",
      "Les passes intélligentes et créatives sont peu présentes dans le jeu de l'équipe.",
      "Les passes intélligentes et créavites sont rarissimes dans le jeu de l'équipe.",
    ],
    smartPassesRatio: [
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes est belle et bien présente dans l'effectif.",
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes est bien présente dans l'effectif.",
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes est suffisamment présente dans l'effectif.",
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes n'est pas suffisamment présente dans l'effectif.",
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes est peu présente dans l'effectif.",
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes est absente de l'effectif.",
    ],
    throughPasses: [
      "Les mouvements dans la profondeur sont de très bonnes qualités et favorisent les passes en profondeurs.",
      "Les mouvements dans la profondeur sont de bonnes qualités et favorisent les passes en profondeurs.",
      "Les mouvements dans la profondeur sont d' assez bonnes qualités et favorisent quelques passes en profondeurs.",
      "Les mouvements dans la profondeur sont d' assez mauvaises qualités et ne favorisent pas suffisamment les passes en profondeurs.",
      "Les mouvements dans la profondeur sont de mauvaises qualités et ne favorisent pas les passes en profondeurs.",
      "Les mouvements dans la profondeur sont de très mauvaises qualités et ne favorisent pas les passes en profondeurs.",
    ],
    throughPassesRatio: [
      "Celles-ci sont vraiment précises et alimentent une très large proportion de ces appels.",
      "Celles-ci sont précises et alimentent une large proportion de ces appels de balles.",
      "Celles-ci sont assez précises et alimentent une légère proportion de ces appels de balles.",
      "Celles-ci ne sont pas assez précises et n'alimentent qu'une très petite proportion de ces appels de balles.",
      "Celles-ci ne sont pas précises et n'alimentent qu'une petite proportion de ces appels de balles.",
      "Celles-ci ne sont pas très précises et n'alimentent qu'une infime proportion de ces appels de balles.",
    ],
    crosses: [
      "L' équipe effectue énormément de centres,",
      "L' équipe effectue beaucoup de centres,",
      "L' équipe effectue assez de centres,",
      "L' équipe effectue assez peu de centres,",
      "L' équipe effectue peu de centres,",
      "L' équipe effectue très peu de centres,",
    ],
    crossesRatio: [
      "ils sont très précis et donc potentiellement prolifiques.",
      "ils sont précis et donc potentiellement prolifiques.",
      "ils sont assez précis et donc potentiellement prolifiques.",
      "ils sont assez imprécis et donc peu prolifiques.",
      "ils sont souvent imprécis et donc rarement prolifiques.",
      "ils sont trop souvent imprécis donc très rarement prolifiques.",
    ],
    passToFinalThirds: [
      "Une grande proportion de passes est effectuée dans le tiers offensif",
      "Une bonne proportion de passes est effectuée dans le tiers offensif",
      "Une faible proportion de passes est effectuée dans le tiers offensif",
      "Une petite proportion de passes est effectuée dans le tiers offensif",
      "Une très petite proportion de passes est effectuée dans le tiers offensif",
    ],
    passToFinalThirdsRatio: [
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est très satisfaisant.",
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est satisfaisant.",
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est assez moyen.",
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est assez bas.",
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est vraiment bas.",
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est vraiment trop bas.",
    ],
    shortLongRatio: [
      "Les passes longues sont très souvent utilisées",
      "Les passes longues sont souvent utilisées",
      "Les passes longues sont assez souvent utilisées",
      "Les passes longues sont assez peu utilisées",
      "Les passes longues sont rarement utilisées",
      "Les passes longues sont très rarement utilisées",
    ],
    longPassesRatio: [
      "le pourcentage de réussite qui en découle est très bon.",
      "le pourcentage de réussite qui en découle est bon.",
      "le pourcentage de réussite qui en découle est assez bon.",
      "le pourcentage de réussite qui en découle n'est pas assez bon.",
      "le pourcentage de réussite qui en découle n'est pas bon.",
      "le pourcentage de réussite qui en découle n'est vraiment pas bon.",
    ],
    passToPenaltyAreas: [
      "Les joueurs évoluant sur le front de l’attaque reçoivent régulièrement des ballons dans la surface de réparation adverse.",
      "Les joueurs évoluant sur le front de l’attaque reçoivent souvent des ballons dans la surface de réparation adverse.",
      "Les joueurs évoluant sur le front de l’attaque reçoivent assez souvent des ballons dans la surface de réparation adverse.",
      "Les joueurs évoluant sur le front de l’attaque ne reçoivent qu'assez peu de ballons dans la surface de réparation adverse.",
      "Les joueurs évoluant sur le front de l’attaque ne reçoivent que peu de ballons dans la surface de réparation adverse.",
      "Les joueurs évoluant sur le front de l’attaque ne reçoivent que très peu de ballons dans la surface de réparation adverse.",
    ],
    passToPenaltyAreasRatio: [
      "Le niveau de réussite des passes est largement à l'avantage de l'équipe, qui a ainsi l'occasion d'accroitre le danger.",
      "Le niveau de réussite des passes est à l'avantage de l'équipe, qui a ainsi l'occasion d'accroitre le danger.",
      "Le niveau de réussite des passes est légèrement à l'avantage de l'équipe, qui a ainsi l'occasion d'accroitre le danger.",
      "Le niveau de réussite des passes est légèrement défavorable à l'équipe, qui n'a pas suffisament d'occasion d'accroire le danger.",
      "Le niveau de réussite des passes est défavorable à l'équipe, qui a peu d'occasion d'accroire le danger.",
      "Le niveau de réussite des passes est défavorable à l'équipe, qui a très peu d'occasion d'accroire le danger.",
    ],
  },
  PERCUSSION: {
    dribbles: [
      "Les tentatives de dribbles sont très nombreuses",
      "Les tentatives de dribbles sont nombreuses",
      "Les tentatives de dribbles sont assez nombreuses",
      "Les tentatives de dribbles ne sont pas assez nombreuses",
      "Les tentatives de dribbles ne sont pas nombreuses",
      "Les tentatives de dribbles ne sont pas très nombreuses",
    ],
    dribblesRatio: [
      "le taux de réussite de ces dernières est très favorables. Ce ratio met en évidence l'excellente technique individuelle des protagonistes !",
      "le taux de réussite de ces dernières est favorables. Ce ratio met en évidence la qualité technique individuelle des protagonistes !",
      "le taux de réussite de ces dernières est assez favorable. Ce ratio  met en évidence la qualité technique individuelle de certains protagonistes !",
      "le taux de réussite de ces dernières n'est pas suffisamment favorable. Ce ratio met en évidence la qualité technique individuelle de certains protagonistes !",
      "le taux de réussite de ces dernières est défavorable. Ce ratio met en évidence le peu de qualité technique individuelle de certains protagonistes !",
      "le taux de réussite de ces dernières est défavorable. Ce ratio met en évidence le manque de qualité technique individuelle de certains protagonistes !",
    ],
    progressiveRun: [
      "Les courses en direction du but adverse sont très largement répétées.",
      "Les courses en direction du but adverse sont largement répétées.",
      "Les courses en direction du but adverse sont assez répétées.",
      "Les courses en direction du but adverse ne sont pas suffisamment répétée.",
      "Les courses en direction du but adverse sont rarement répétées.",
      "Les courses en direction du but adverse sont très rarement répétées.",
    ],
    progressivePasses: [
      "La proportion des passes réalisées dans la course des joueurs est très élevée.",
      "La proportion des passes réalisées dans la course des joueurs est élevée.",
      "La proportion des passes réalisées dans la course des joueurs est assez élevée.",
      "La proportion des passes réalisées dans la course des joueurs n’est pas assez élevée.",
      "La proportion des passes réalisées dans la course des joueurs est trop faible.",
      "La proportion des passes réalisées dans la course des joueurs est beaucoup trop faible.",
    ],
    progressivePassesRatio: [
      "Elles sont très souvent dans le bon tempo et favorisent ainsi l'avancée du bloc au plus près de la surface adverse.",
      "Elles sont souvent dans le bon tempo et favorisent ainsi l'avancée du bloc au plus près de la surface adverse.",
      "Elles sont suffisamment données dans le bon tempo et pour favoriser l'avancée du bloc au plus près de la surface adverse.",
      "Elles ne sont pas suffisamment données dans le bon tempo et ne favorisent donc pas l'avancée du bloc au plus près de la surface adverse.",
      "Elles sont rarement données dans le bon tempo et ne favorisent donc pas l'avancée du bloc au plus près de la surface adverse.",
      "Elles sont très rarement données dans le bon tempo et ne favorisent donc pas l'avancée du bloc au plus près de la surface adverse.",
    ],
  },
  RECOVERY: {
    losses: [
      "L' application des joueurs est mise en évidence car ils perdent vraiment moins de ballons que ses concurrents.",
      "L' application des joueurs est mise en évidence car ils perdent beaucoup moins de ballons que ses concurrents.",
      "L' application des joueurs est mise en évidence car ils perdent moins de ballons que ses concurrents.",
      "L' absence d'application des joueurs est mise en évidence car ils perdent plus de ballons que ses concurrents.",
      "L' absence d'application des joueurs est mise en évidence car ils perdent beaucoup plus de ballons que ses concurrents.",
      "L' absence d'application des joueurs est mise en évidence car ils perdent vraiment beaucoup plus de ballons que ses concurrents.",
    ],
    interceptions: [
      "Le taux d’interceptions est très élevé et révèle un sens du placement et d’anticipation très important des joueurs.",
      "Le taux d’interceptions est élevé et révèle un sens du placement et d’anticipation important des joueurs.",
      "Le taux d’interceptions est assez élevé et révèle un sens du placement et d’anticipation suffisant des joueurs.",
      "Le taux d’interceptions est assez faible et révèle un sens du placement et de l’anticipation inssufisant de la part des joueurs.",
      "Le taux d’interceptions est faible et révèle un sens du placement et de l’anticipation décevant de la part des joueurs.",
      "Le taux d’interceptions est très faible et révèle un sens du placement et de l’anticipation très décevant de la part des joueurs.",
    ],
    interceptionsOpponent: [
      "Comme évoqué dans la section distribution, les passes sont très précises rendant ainsi les interceptions adverses très compliquées.",
      "Comme évoqué dans la section distribution, les passes sont précises rendant ainsi les interceptions adverses compliquées.",
      "Comme évoqué dans la section distribution, les passes sont assez précises rendant ainsi les interceptions adverses un peu compliquées.",
      "Comme évoqué dans la section distribution, les passes sont assez imprécises  facilitant ainsi quelques interceptions adverses.",
      "Comme évoqué dans la section distribution, les passes sont imprécises favorisant ainsi les interceptions adverses.",
      "Comme évoqué dans la section distribution, les passes sont trop imprécises favorisant ainsi les interceptions adverses.",
    ],
    recoveries: [
      "L’ équipe montre une très grande efficacité dans la récupération du ballon et laisse par conséquent très peu d'espoir aux adversaires.",
      "L’ équipe montre une grande efficacité dans la récupération du ballon et laisse par conséquent peu d'espoir aux adversaires.",
      "L’ équipe montre une efficacité assez modérée dans la récupération du ballon et par conséquent de rares espoir aux adversaires.",
      "L’ équipe montre assez peu d'efficacité  dans la récupération du ballon et offre par conséquent des opportunités aux adversaires.",
      "L’ équipe montre peu d'efficacité dans la récupération du ballon et offre par conséquent trop d'opportunités aux adversaires.",
      "L’ équipe montre très peu d'efficacité dans la récupération du ballon et offre par conséquent beaucoup trop d'opportunités aux adversaires.",
    ],
    duels: [
      "Les joueurs multiplient très fortement le nombre de duels pour tenter de récupérer les ballons,",
      "Les joueurs multiplient fortement le nombre de duels pour tenter de récupérer les ballons,",
      "Les joueurs multiplient assez fortement le nombre de duels pour tenter de récupérer les ballons,",
      "Les joueurs ne multiplient pas assez le nombre de duels pour tenter de récupérer les ballons,",
      "Les joueurs ne multiplient pas beaucoup le nombre de duels pour tenter de récupérer les ballons,",
      "Les joueurs ne multiplient presque pas le nombre de duels pour tenter de récupérer les ballons,",
    ],
    duelsRatio: [
      "dans l'ensemble le niveau de réussite est vraiment favorable. En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
      "dans l'ensemble le niveau de réussite est favorable.En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
      "dans l'ensemble le niveau de réussite est assez favorable.En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
      "dans l'ensemble le niveau de réussite n'est pas suffisamment favorable. En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
      "dans l'ensemble le niveau de réussite est défavorable. En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
      "dans l'ensemble le niveau de réussite est vraiment défavorable. En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
    ],
    defensiveDuelsRatio: [
      "- Une très grande majorité des duels défensifs sont gagnés par les joueurs",
      "- Une majorité des duels défensifs sont gagnés par les joueurs",
      "- Une petite majorité des duels défensifs sont gagnés par les joueurs",
      "- Une petite majorité des duels défensifs sont perdus par les joueurs",
      "- Une majorité des duels défensifs sont perdus par les joueurs",
      "- Une grande majorité des duels défensifs sont perdus par les joueurs",
    ],
    dribblesSuccessful: [
      "les tentatives de dribbles adverses sont très souvent avortées.",
      "les tentatives de dribbles adverses sont souvent avortées.",
      "les tentatives de dribbles adverses sont suffisamment avortées.",
      "les tentatives de dribbles adverses ne sont pas assez avortées.",
      "les tentatives de dribbles adverses sont rarement avortées.",
      "les tentatives de dribbles adverses sont très rarement avortées.",
    ],
    aerialDuelsRatio: [
      "- Le timming dans les duels aériens est excellent, car ils sont très souvent gagnés par l’équipe.",
      "- Le timming dans les duels aériens est bon, car ils sont souvent gagnés par l’équipe.",
      "- Le timming dans les duels aériens est tout juste acceptable, car ils ne sont que légèrement gagnés par l’équipe.",
      "- Le timming dans les duels aériens n'est pas assez bon, car ils sont légèrement gagnés par les adversaires.",
      "- Le timming dans les duels aériens est mauvais, car ils sont souvent gagnés par les adversaires.",
      "- Le timming dans les duels aériens est très mauvais, car ils sont très souvent gagnés par les adversaires.",
    ],
    slidingTacklesRatio: [
      "- Les tacles glissés sont bien maitrisés car très peu de fautes sont sifflées contre les protagonistes.",
      "- Les tacles glissés sont bien maitrisés car peu de fautes sont sifflées contre les protagonistes.",
      "- Les tacles glissés sont assez bien maitrisés car seulement quelques fautes sont sifflées contre les protagonistes.",
      "- Les tacles glissés sont assez mal maitrisés car quelques fautes sont sifflées contre les protagonistes.",
      "- Les tacles glissés sont mal maitrisés car trop de fautes sont sifflées contre les protagonistes.",
      "- Les tacles glissés sont très mal maitrisés car beaucoup trop de fautes sont sifflées contre les protagonistes.",
    ],
    groundDuelsRatio: [
      "- Les joueurs font preuve d’une très bonne agressivité et remportent un nombre très important de ballons dans les duels au sol.",
      "- Les joueurs font preuve d’une bonne agressivité et remportent un nombre important de ballons dans les duels au sol.",
      "- Les joueurs font preuve d’une agressivité suffisante et remportent un nombre assez élevé de ballons dans les duels au sol.",
      "- Les joueurs ne font pas preuve d’une agressivité suffisante et perdent trop de ballon dans les duels au sol.",
      "- Les joueurs font preuve d’un manque important d'agressivité et perdent beaucoup de ballon dans les duels au sol.",
      "- Les joueurs font preuve d’un manque très important d'agressivité et perdent beaucoup trop de ballon dans les duels au sol.",
    ],
    looseBallDuelsRatio: [
      "- Les joueurs font preuvent d'une très bonne réactivité et récupèrent un nombre signifiant de ballons.",
      "- Les joueurs font preuvent d'une bonne réactivité et récupèrent un nombre signifiant de ballons.",
      "- Les joueurs font preuvent d'une assez bonne réactivité et récupèrent quelques ballons.",
      "- Les joueurs ne font pas preuve d'une réactivité suffisante et ne écupèrent qu'un petit nombre de ballons.",
      "- Les joueurs manquent de réactivité pour pouvoir récupérer un nombre signifiant de ballons.",
      "- Les joueurs manquent terriblement de réactivité pour pouvoir récupérer un nombre très important de ballons.",
    ],
  },
  FREEKICKS: {
    cornersRatio: [
      "Les corners sont très bien négociés, car un très grand nombre d'entre eux aboutissent à une action dangereuse pour la défense adverse.",
      "Les corners sont bien négociés, car un nombre important d'entre eux aboutissent à une action dangereuse pour la défense adverse.",
      "Les corners sont moyennement bien négociés, car un nombre insuffisant d'entre eux aboutissent à une action dangereuse pour la défense adverse.",
      "Les corners sont mal négociés, car un petit nombre d'entre eux aboutissent à une action dangereuse pour la défense adverse.",
      "Les corners sont très mal négociés, car un trop petit nombre d'entre eux aboutissent à une action dangereuse pour la défense adverse.",
    ],
    freekicksRatio: [
      "Les opportunités de marquer sur coup francs indirect sont très importantes car ils sont très souvent cadrés.",
      "Les opportunités de marquer sur coup francs indirect sont importantes car ils sont très souvent cadrés.",
      "Les opportunités de marquer sur coup francs indirect sont modérée car ils ne sont pas suffisament cadrés.",
      "Les opportunités de marquer sur coup francs indirect sont très faible car ils sont rarement cadrés.",
      "Les opportunités de marquer sur coup francs indirect sont beaucoup trop faible car ils sont très rarement cadrés.",
    ],
    directFreeKicksRatio: [
      "Pour les coups francs directs, la performance des tireurs représentent un danger très sérieux pour le gardien adverse.",
      "Pour les coups francs directs, la performance des tireurs représentent un danger sérieux pour le gardien adverse.",
      "Pour les coups francs directs, la performance des tireurs représentent un danger modéré pour le gardien adverse.",
      "Pour les coups francs directs, la performance des tireurs ne représentent pas un danger important pour le gardien adverse.",
      "Pour les coups francs directs, la performance des tireurs ne représentent pas un danger très important pour le gardien adverse.",
    ],
    freeKicksWithShotRatio: [
      "Il y a une très grande majotié d'actions qui commencent par une phases de jeux arretés et qui se soldent par un tirs.",
      "Il y a une grande majotié d'actions qui commencent par une phases de jeux arretés et qui se soldent par un tirs.",
      "Il y a une petite majotié d'actions qui commencent par une phases de jeux arretés et qui se soldent par un tirs.",
      "Il y a peu d'actions qui commencent par une phases de jeux arretés et qui se soldent par un tirs.",
      "Il y a très peu d'actions qui commencent par une phases de jeux arretés et qui se soldent par un tirs.",
    ],
  },
  PRESSING: {
    ppda: [
      "L' équipe est très agressive sur le porteur du ballon, elle cherche une récupération haute sur le terrain en coupant très rapidement les transitions adverses.",
      "L' équipe est agressive sur le porteur du ballon, elle cherche une récupération haute sur le terrain en coupant rapidement les transitions adverses.",
      "L’ équipe est suffisamment agressive sur le porteur du ballon, elle cherche une récupération assez haute sur le terrain en coupant aussi vite que possible les transitions adverses.",
      "L’ équipe ne montre pas suffisamment d’agressivité sur le porteur du ballon, elle ne peut espérer qu’une récupération assez basse sur le terrain, car les adversaires ont un peu de temps pour progresser vers la surface.",
      "L’ équipe ne montre pas beaucoup agressivité sur le porteur du ballon, elle ne peut espérer qu’une récupération basse sur le terrain, car les adversaires ont le temps de temps pour progresser vers la surface.",
      "L’ équipe ne montre quasiment pas agressivité sur le porteur du ballon, elle ne peut espérer qu’une récupération trop basse sur le terrain, car les adversaires ont énormément de temps pour progresser vers la surface.",
    ],
    challengeIntensity: [
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est très élevé.",
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est élevé.",
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est assez élevé.",
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est assez faible.",
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est faible.",
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est très faible.",
    ],
  },
  POSSESSION: {
    groupPossession: [
      "Lorsqu'elle est en possession du ballon et doit faire le jeu, son ratio de productivité est vraiment favorable. Elle impose fortement son style de jeu tout en maitrisant parfaitement ses concurrents.",
      "Lorsqu'elle est en possession du ballon et doit faire le jeu, son ratio de productivité est favorable. Elle impose fortement son style de jeu tout en maitrisant parfaitement ses concurrents. ",
      "Lorsqu'elle est en possession du ballon et doit faire le jeu, son ratio de productivité est assez favorable. Elle impose timidement son style de jeu tout en maitrisant légèrement ses concurrents.",
      "Lorsqu'elle est en possession du ballon et doit faire le jeu, son ratio de productivité n’est pas suffisamment favorable. Elle impose assez rarement son style de jeu et laisse un peu trop de possibilités à ses concurrents.",
      "Lorsqu'elle est en possession du ballon et doit faire le jeu, son ratio de productivité est mauvais. Elle impose rarement son style de jeu et laisse trop de possibilités à ses concurrents. ",
      "Lorsqu'Elle est en possession du ballon et doit faire le jeu, son ratio de productivité est trop mauvais. Elle impose très rarement son style de jeu et laisse beaucoup trop de possibilités à ses concurrents.",
    ],
    groupOpponentPossession: [
      "Quand elle n’a pas le ballon, elle n’en est pas moins hyper compétitive. Son organisation et jeu sans ballon lui confère une très bonne solidité défensive, mais aussi une redoutable efficacité offensive.",
      "Quand elle n’a pas le ballon, elle n’en est pas moins compétitive. Son organisation et jeu sans ballon lui confère une  bonne solidité défensive, mais aussi une efficacité offensive favorable.",
      "Quand elle n’a pas le ballon, elle reste assez compétitive. Son organisation et jeu sans ballon lui confère une assez bonne solidité défensive, mais aussi une efficacité offensive suffisante.",
      "Quand elle n’a pas le ballon, elle n'est pas suffisamment compétitive. Son organisation et jeu sans ballon lui confère une petite fragilité défensive, mais aussi une efficacité offensive insuffisante.",
      "Quand elle n’a pas le ballon, elle est rarement compétitive. Son organisation et jeu sans ballon lui confère une grande fragilité défensive, mais aussi une efficacité offensive trop faible.",
      "Quand elle n’a pas le ballon, elle est rarement compétitive. Son organisation et jeu sans ballon lui confère une très grande fragilité défensive, mais aussi une efficacité offensive beaucoup trop faible.",
    ],
  },
};

export const TPI_LINK: any = {
  OFFENSIF: {
    Goals: ["goals", "goalsEfficiency"],
    GoalsMean: ["goalMean"],
    cleanSheets: ["cleanSheets"],
    Shots: ["groupShots.shots", "groupShots.shotsRatio"],
    shotsOutsideConfidence: [
      "groupShotDistance.shotOutsideBox",
      "groupShotDistance.shotsOutsideConfidence",
    ],
    headShotsRatio: [
      "groupHeadShots.headShotsRatio",
      "groupHeadShots.headShotsOnTarget",
    ],
    withShots: ["withShots"],
    counterAttacks: ["counterAttacks"],
    Offsides: ["Offsides"],
  },
  DEFENSIF: {
    goals2: ["goals2", "cleanSheets2"],
    goalMean2: ["goalMean2"],
    groupPasses: ["groupPasses"],
    attacks: ["groupAttacks.attacks", "groupAttacks.withShots2"],
    shots2: ["shots2", "groupShotDistance2.shotsFromBox2"],
    shotBlocked2: [
      "groupOpportunityBlocked.shotBlocked2",
      "groupHeadShot2.headShotsRatio2",
    ],
    crossesTotal2: [
      "groupOpportunityBlocked.crossesTotal2",
      "groupOpportunityBlocked.crossesSuccessful2",
    ],
    crossesBlocked2: ["groupOpportunityBlocked.crossesBlocked2"],
    counterAttacks2: ["counterAttacks2"],
    corners2: ["groupFreeKicks.corners2", "groupFreeKicks.cornersRatio2"],
    freeKicksWithShot2: [
      "groupFreeKicks.freeKicksWithShot2",
      "groupFreeKicks.freeKicksWithShotRatio2",
    ],
    opponentOffsides2: ["opponentOffsides2"],
    gkSaves2: ["gkSaves2"],
  },
  DISTRIBUTION: {
    passes: ["passes", "passesRatio"],
    shortLongRatio: [
      "groupPassesDistances.shortLongRatio",
      "groupPassesDistances.longPassesRatio",
    ],
    keyPasses: ["groupkeyPasses.keyPasses"],
    keyPassesRatio: ["groupkeyPasses.keyPassesRatio"],
    smartPasses: ["groupSmartPasses.smartPasses"],
    smartPassesRatio: ["groupSmartPasses.smartPassesRatio"],
    crosses: ["groupCrosses.crosses", "groupCrosses.crossesRatio"],
    throughPasses: ["groupThroughPasses.throughPasses"],
    throughPassesRatio: ["groupThroughPasses.throughPassesRatio"],
    passToFinalThirds: [
      "groupPassToFinalThirds.passToFinalThirds",
      "groupPassToFinalThirds.passToFinalThirdsRatio",
    ],
    passToPenaltyAreas: ["groupPassesZone.passToPenaltyAreas"],
    "groupPassesZone.passToPenaltyAreasRatio": [
      "groupPassesZone.passToPenaltyAreasRatio",
    ],
    assists: ["assists"],
  },
  PERCUSSION: {
    dribbles: ["groupDribbles.dribbles", "groupDribbles.dribblesRatio"],
    progressiveRun: ["progressiveRun"],
    progressivePasses: ["groupProgessivePasses.progressivePasses"],
    progressivePassesRatio: ["groupProgessivePasses.progressivePassesRatio"],
  },
  RECOVERY: {
    losses: ["losses"],
    interceptions: ["interceptions"],
    interceptionsOpponent: ["interceptionsOpponent"],
    recoveries: ["recoveries"],
    duels: ["groupDuels.duels", "groupDuels.duelsRatio"],
    defensiveDuels: [
      "groupDefensiveDuels.defensiveDuels",
      "groupDefensiveDuels.defensiveDuelsRatio",
    ],
    offensiveDuels: [
      "groupOffensiveDuels.offensiveDuels",
      "groupOffensiveDuels.offensiveDuelsRatio",
    ],
    aerialDuels: ["groupAerialDuels.aerialDuelsRatio"],
    slidingTacklesRatio: [
      "groupSlidingTackles.slidingTackles",
      "groupSlidingTackles.slidingTacklesRatio",
    ],
    groundDuels: [
      "groupGroundDuels.groundDuels",
      "groupGroundDuels.groundDuelsRatio",
    ],
    looseBallDuels: ["grouplooseBallDuels.looseBallDuelsRatio"],
    dribblesSuccessful: ["groupDribblesAgainst.dribblesSuccessful"],
    fouls: ["fouls"],
  },
  FREEKICKS: {
    cornersRatio: ["cornersRatio"],
    freekicksRatio: ["freekicksRatio"],
    directFreeKicksRatio: ["directFreeKicksRatio"],
    freeKicksWithShotRatio: ["freeKicksWithShotRatio"],
  },
  PRESSING: {
    ppda: ["groupPressing.ppda"],
    challengeIntensity: ["groupPressing.challengeIntensity"],
  },
  POSSESSION: {
    groupPossession: ["groupPossession"],
    groupOpponentPossession: ["groupOpponentPossession"],
  },
};

export const TPI_TRANSLATION: any = {
  OFFENSIF: {
    Goals: "Buts",
    withShots: "Attaques",
    Shots: "Tirs",
    headShotsRatio: "Jeu Aérien",
    Offsides: "Hors-Jeu",
  },
  DEFENSIF: {
    goals2: "Buts",
    groupPasses: "Passes",
    attacks: "Actions",
    corners2: "Coups de Pieds Arrêtés",
    opponentOffsides2: "Hors-Jeu",
    gkSaves2: "Gardien",
  },
  DISTRIBUTION: {
    passes: "Passes",
    passToFinalThirds: "Passes dans le tiers offensif",
    keyPasses: "Passes Clefs",
    throughPasses: "Passes en Profondeur",
    smartPasses: "Passes Créatives",
    crosses: "Centres",
    passToPenaltyAreas: "Passes dans la surface de réparation",
    assists: "Passes Décisives",
  },
  PERCUSSION: {
    dribbles: "Dribbles",
    progressiveRun: "Accélérations",
    progressivePasses: "Passes dans la course",
  },
  RECOVERY: {
    losses: "Pertes de Balles",
    interceptions: "Interceptions",
    recoveries: "Récupération",
    duels: "Duels",
  },
  PRESSING: {
    ppda: "Intensité du Pressing",
  },
  FREEKICKS: {
    cornersRatio: "Corners",
    freekicksRatio: "Coups Franc",
  },
  POSSESSION: {
    groupPossession: "Possession",
    groupOpponentPossession: "Possession adverse",
  },
};

export const SENTENCE_SUMMARY: any = {
  goals: ["Nombre de buts", "Peu de buts"],
  goalsEfficiency: ["Efficacité devant le but", "Efficacité devant le but"],
  shots: ["Nombre de tirs", "Nombre de tirs"],
  shotsOutsideConfidence: [
    "Qualité des frappes lointaines",
    "Qualité des frappes lointaines",
  ],
  headShotsRatio: ["Bon ratio du jeu aérien", "Manque de jeu aérien"],
  headShotsOnTarget: ["Qualité du jeu de tête", "Qualité du jeu de tête"],
  Offsides: ["Peu de hors-jeu", "Trop de hors-jeu"],
  withShots: [
    "Nombre d'offensives dangereuses",
    "Peu d'offensives dangereuses",
  ],
  counterAttacks: ["Fréquence des contre-attaques", "Peu de contre-attaques"],
  goals2: ["Peu de buts encaissés", "Trop de buts encaissés"],
  shots2: ["Peu d'occasions subies", "Trop d'occasions subies"],
  counterAttacks2: [
    "Peu de contre-attaques subies",
    "Trop de contre-attaques subies",
  ],
  headShotsOnTarget2: ["Marquage sur les centres", "Marquage sur les centres"],
  gkSaves2: ["Performance du gardien", "Fragilité du gardien"],
  opponentOffsides2: ["Alignement défensif", "Alignement défensif"],
  crossesTotal2: ["Peu de centres subis", "Trop de centres subis"],
  withShot2: ["Peu d'offensives dangereuses", "Trop d'offensives dangereuses"],
  groupFreeKicks: ["Coups de pied arrêtés", "Coups de pied arrêtés"],
  passes: ["Maitrise du jeu", "Peu de maitrise du jeu"],
  passesRatio: ["Précision des passes", "Précision des passes"],
  longPassesRatio: ["Précision du jeu long", "Précision du jeu long"],
  shotAssist: ["Animation offensive ", "Animation offensive "],
  groupkeyPasses: ["Passes Clés", "Passes Clés"],
  groupThroughPasses: ["Passes en profondeur", "Passes en profondeur"],
  groupCrosses: ["Centres", "Centres"],
  groupPassToFinalThirds: [
    "Passes dans le tiers adverse",
    "Passes dans le tiers adverse",
  ],
  progressiveRun: [
    "Nombre de courses vers l'avant",
    "Nombre de courses vers l'avant",
  ],
  dribblesRatio: ["Qualité des dribbles", "Qualité des dribbles"],
  progressivePasses: [
    "Nombre de passes progressives",
    "Peu de passes progressives",
  ],
  losses: ["Peu de ballons perdus", "Trop de ballons perdus"],
  interceptions: ["Nombre d’interceptions", "Manque d’interceptions"],
  recoveries: ["Récupérations du ballon", "Récupérations du ballon"],
  interceptionsOpponent: ["Interceptions adverses", "Interceptions adverses"],
  defensiveDuelsRatio: ["Duels défensifs", "Duels défensifs"],
  aerialDuelsRatio: ["Duels aériens", "Duels aériens"],
  slidingTacklesRatio: ["Qualité des tacles", "Qualité des tacles"],
  looseBallDuelsRatio: [
    "Réactivité dans la récupération du ballon",
    "Réactivité dans la récupération du ballon",
  ],
  dribblesSuccessful: [
    "Réussite des dribbles adverses",
    "Réussite des dribbles adverses",
  ],
  groupPossession: ["Domination & Dangerosité", "Domination & Dangerosité"],
  groupOpponentPossession: [
    "Récupération & Efficacité",
    "Récupération & Efficacité",
  ],
  cornersRatio: ["Gestion des corners", "Gestion des corners"],
  freekicksRatio: ["Coups francs indirects", "Coups francs indirects"],
  directFreekicksRatio: ["Coups francs directs", "Coups francs directs"],
  freeKicksWithShotRatio: ["Coups francs dangereux", "Coups francs dangereux"],
  groupPressing: ["Intensité du Pressing", "Intensité du Pressing"],
};
