export const TPI_CATEGORY_LABEL: any = {
  OFFENSIF: "OFFENSIVE",
  DEFENSIF: "DEFENSIVE",
  DISTRIBUTION: "DISTRIBUTION",
  PERCUSSION: "PERCUSSION",
  RECOVERY: "REGAIN POSSESSION",
  PRESSING: "PRESSING",
  FREEKICKS: "SET PIECES",
  POSSESSION: "GAME SET",
};

export const TPI_ORDER_CHART: any = {
  OFFENSIF: "OFFENSIVE",
  DEFENSIF: "DEFENSIVE",
  DISTRIBUTION: "DISTRIBUTION",
  PERCUSSION: "PERCUSSION",
  RECOVERY: "REGAIN POSSESSION",
  PRESSING: "PRESSING",
  FREEKICKS: "SET PIECES",
  POSSESSION: "GAME SET",
};

export const TPI_SUMMARY: any = {
  OFFENSIF: [
    "L’ équipe présente des statistiques offensives très intéressantes par rapport à celles de ses adversaires.",
    "L’ équipe présente des statistiques offensives intéressantes par rapport à celles de ses adversaires.",
    "L’ équipe présente des statistiques offensive assez intéressantes par rapport à celles de ses adversaires.",
    "L’ équipe présente des statistiques offensives assez faibles par rapport à celles de ses adversaires.",
    "L’ équipe présente des statistiques offensives faibles par rapport à celles de ses adversaires.",
    "L’ équipe présente des statistiques offensives trop faibles par rapport à celles de ses adversaires.",
  ],
  DEFENSIF: [
    "Les statistiques défensives sont très solides car elles mettent en lumière les très rare difficultés provoquées par les adversaires.",
    "Les statistiques défensives sont solides car elles mettent en lumière les rare difficultés provoquées par les adversaires.",
    "Les statistiques défensives sont tout juste acceptables car elles mettent en lumière les quelques difficultés provoquées par les adversaires.",
    "Les statistiques défensives ne sont pas assez solides car elles mettent en lumière le niveau du danger que les adversaires arrivent à créer.",
    "Les statistiques défensives sont très faible car elles mettent en lumière le niveau du danger que les adversaires arrivent à créer.",
    "Les statistiques défensives sont vraiment trop faible car elles mettent en lumière le niveau du danger que les adversaires arrivent à créer.",
  ],
  DISTRIBUTION: [
    "L’ équipe a gagné la maitrise du jeu, car le volume et le bon dosage des passes lui permet de mettre ses adversaires sous haute pression.",
    "L’ équipe a gagné la maitrise du jeu, car le volume et le bon dosage des passes lui permet de mettre ses adversaires sous pression.",
    "L’ équipe a légérement gagné la maitrise du jeu, car le volume et le bon dosage des passes lui permet de mettre ses adversaires sous pression.",
    "L’ équipe a perdu la maitrise du jeu, car le volume et le mauvais dosage des passes ne permettent que moyennement de mettre les adversaires sous pression.",
    "L’ équipe a perdu la maitrise du jeu, car le volume et le mauvais dosage des passes ne permettent que rarement de mettre les adversaires sous pression.",
    "L’ équipe a perdu la maitrise du jeu, car le volume et le mauvais dosage des passes ne permettent que très rarement de mettre les adversaires sous pression.",
  ],
  PERCUSSION: [
    "Les qualités de percussion sont très présentes dans la construction du jeu, l'équipe à ainsi davantage de possibilités face à des blocs défensifs regroupés et compacts.",
    "Les qualités de percussion sont présentes dans la construction du jeu, l'équipe à ainsi davantage de possibilités face à des blocs défensifs regroupés et compacts.",
    "Les qualités de percussion sont assez présentes dans la construction du jeu, l'équipe à ainsi quelques possibilités face à des blocs défensifs regroupés et compacts.",
    "Les qualités de percussion ne sont pas suffisamment présentes dans la construction du jeu, l'équipe manque parfois de solutions face à certains blocs défensifs regroupés et compacts.",
    "Les qualités de percussion sont trop rares dans la construction du jeu, l'équipe est ainsi en mal de solutions face à des blocs défensifs regroupés et compacts.",
    "Les qualités de percussion sont vraiment trop rares dans la construction du jeu, l'équipe est ainsi en mal de solutions face à des blocs défensifs regroupés et compacts.",
  ],
  RECOVERY: [
    "Le niveau de rigueur dans les duels, la récupération et le placement dont fait preuve l'équipe est très élevé et lui permet de réaliser des performances de très haut standing.",
    "Le niveau de rigueur dans les duels, la récupération et le placement dont fait preuve l'équipe est élevé et lui permet de réaliser des performances de haut standing.",
    "Le niveau de rigueur dans les duels, la récupération et le placement dont fait preuve l'équipe est assez élevé et lui permet de réaliser des performances d'un assez haut standing.",
    "Le niveau de rigueur dans les duels, la récupération et le placement dont fait preuve l'équipe n'est pas assez élevé et ne l'aide pas à réaliser des performances d'un assez haut standing.",
    "Le niveau de rigueur dans les duels, la récupération et le placement dont fait preuve l'équipe est faible et ne l'aide pas à réaliser des performances d'un haut standing.",
    "Le niveau de rigueur dans les duels, la récupération et le placement dont fait preuve l'équipe est très faible et ne l'aide pas à réaliser des performances d'un très haut standing",
  ],
  PRESSING: [
    "L’ équipe a réalisé un pressing de très haute intensité qui met en évidence, l' excellent niveau physique et tactique des joueurs.",
    "L’ équipe a réalisé un pressing de haute intensité qui met en évidence le très bon niveau physique et tactique des joueurs.",
    "L’ équipe a réalisé un pressing d'assez haute intensité qui met en évidence un niveau physique et tactique suffisant.",
    "L’ équipe a réalisé un pressing d'assez basse intensité qui met en évidence un niveau physique et tactique insuffisant des joueurs.",
    "L’ équipe a réalisé un pressing de basse intensité qui met en évidence un mauvais niveau physique et tactique des joueurs.",
    "L’ équipe a réalisé un pressing de très basse intensité qui met en évidence un très mauvais niveau physique et tactique des joueurs.",
  ],
  FREEKICKS: [
    "Les opportunités sur les phases de jeux arrêtés sont très bien exploitées.",
    "Les opportunités sur les phases de jeux arrêtés sont bien exploitées.",
    "Les opportunités sur les phases de jeux arrêtés sont moyennement bien exploitées.",
    "Les opportunités sur les phases de jeux arrêtés sont mal exploitées.",
    "Les opportunités sur les phases de jeux arrêtés sont très mal exploitées.",
  ],
  POSSESSION: [
    "L'équipe s'adapte très facilement au style de jeu de ses adversaires, tout en gardant un excellent niveau de performance.",
    "L'équipe s'adapte facilement au style de jeu de ses adversaires, tout en gardant un très bon niveau de performance.",
    "L'équipe s'adapte assez facilement au style de jeu de ses adversaires, tout en gardant un niveau de performance acceptable.",
    "L'équipe s'adapte assez difficilement au style de jeu de ses adversaires, car en fonction de la physionomie du match son niveau de performance est assez mauvais.",
    "L'équipe s'adapte difficilement au style de jeu de ses adversaires, car en fonction de la physionomie du match son niveau de performance est mauvais.",
    "L'équipe s'adapte très difficilement au style de jeu de ses adversaires, car en fonction de la physionomie du match son niveau de performance est très mauvais.",
  ],
};

export const TPI: any = {
  OFFENSIF: {
    goals: [
      "Le nombre de buts inscrit est très élevé",
      "Le nombre de buts inscrit est élevé",
      "Le nombre de buts inscrit est suffisament élevé",
      "Le nombre de buts inscrit n'est pas suffisament élevé",
      "Le nombre de buts inscrit est insuffisant",
      "Le nombre de buts inscrit est très insuffisant",
    ],
    goalsEfficiency: [
      "le taux de conversion des frappes en but excellent.",
      "le taux de conversion des frappes en but très satisfaisant.",
      "le taux de conversion des frappes en but juste satisfaisant.",
      "le taux de conversion des frappes en but pas satisfaisant.",
      "le taux de conversion des frappes en but trop faible.",
      "le taux de conversion des frappes en but vraiment trop faible.",
    ],
    goalMean: [
      "La régularité affiché tout au long de la saison est une grande force.",
      "La régularité affiché tout au long de la saison est une force.",
      "La régularité affiché tout au long de la saison est tout juste acceptable.",
      "L' irrégularité affiché tout au long de la saison est trop moyenne.",
      "L' irrégularité affiché tout au long de la saison est une faiblesse.",
      "L' irrégularité affiché tout au long de la saison est une grande faiblesse.",
    ],
    cleanSheets: [
      "Elle comptabilise d'ailleurs très peu de matchs sans marquer.",
      "Elle comptabilise d'ailleurs peu de matchs sans marquer.",
      "Elle comptabilise d'ailleurs assez peu de matchs sans marquer.",
      "Elle comptabilise d'ailleurs un peu trop de matchs sans marquer.",
      "Elle comptabilise d'ailleurs trop de matchs sans marquer.",
      "Elle comptabilise d'ailleurs beaucoup trop de matchs sans marquer.",
    ],
    withShots: [
      "L' analyse montre que la grande majorité des offensives se concluent par des tirs.",
      "L' analyse montre que la majorité des offensives se concluent par des tirs.",
      "L' analyse montre qu'une légère majorité des offensives se concluent par des tirs.",
      "L' analyse montre qu'une légère minorité des offensives se concluent par des tirs.",
      "L' analyse montre qu'une minorité des offensives se concluent par des tirs.",
      "L’ analyse montre qu'une grande minorité des offensives se concluent par des tirs.",
    ],
    shots: [
      "L' équipe totabilise un nombre de tirs très élevé",
      "L' équipe totabilise un nombre de tirs élevé",
      "L' équipe totabilise un nombre de tirs tout juste suffisant",
      "L’ équipe totabilise un nombre de tirs tout juste insuffisant",
      "L' équipe totabilise un nombre de tirs trop faible",
      "L' équipe totabilise un nombre de tirs vraiment trop faible",
    ],
    shotsRatio: [
      "un niveau de précision très favorable.",
      "un niveau de précision favorable.",
      "un niveau de précision à peine favorable.",
      "un niveau de précision à peine défavorable.",
      "un niveau de précision défavorable.",
      "un niveau de précision extrêmement défavorable.",
    ],
    shotOutsideBox: [
      "La proportion des frappes depuis l’extérieur de la surface est très importante,",
      "La proportion des frappes depuis l’extérieur de la surface est importante,",
      "La proportion des frappes depuis l’extérieur de la surface est assez importante,",
      "La proportion des frappes depuis l’extérieur de la surface est assez limitée,",
      "La proportion des frappes depuis l’extérieur de la surface est limitée,",
      "La proportion des frappes depuis l’extérieur de la surface est très limitée,",
    ],
    shotsOutsideConfidence: [
      "le taux de réussite vraiment bénéfique.",
      "le taux de réussite bénéfique.",
      "le taux de réussite assez bénéfique.",
      "le taux de réussite pas assez bénéfique.",
      "le taux de réussite vraiment pénalisant.",
      "le taux de réussite extrêmement pénalisant.",
    ],
    shotFromBox: [
      "L’ équipe a énormément d'aisance tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
      "L’ équipe a beaucoup d'aisance tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
      "L’ équipe a suffisament d'aisance tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
      "L’ équipe n'a pas suffisament d'aisance tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
      "L’ équipe a trop de déficience tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
      "L’ équipe éprouve beaucoup trop de déficience tactique et technique pour se mettre dans les meilleures dispositions pour marquer.",
    ],
    headShotsRatio: [
      "Proportionnellement au nombre de tirs, les têtes sont très souvent utilisées",
      "Proportionnellement au nombre de tirs, les têtes sont souvent utilisées",
      "Proportionnellement au nombre de tirs, les têtes sont un peu utilisées",
      "Proportionnellement au nombre de tirs, les têtes sont peu utilisées",
      "Proportionnellement au nombre de tirs, les têtes sont rarement utilisées",
      "Proportionnellement au nombre de tirs, les têtes sont très rarement utilisées",
    ],
    headShotsOnTarget: [
      "elles sont très souvent efficaces.",
      "elles sont souvent efficaces.",
      "elles sont tout juste efficaces.",
      "elles ne sont pas assez efficaces.",
      "elles ne sont pas efficaces.",
      "elles ne sont absolument pas efficaces.",
    ],
    Offsides: [
      "Les joueurs sont très rarement en position de hors-jeu.",
      "Les joueurs sont rarement en position de hors-jeu.",
      "Les joueurs sont assez rarement en position de hors-jeu.",
      "Les joueurs sont assez régulièrement en position de hors-jeu.",
      "Les joueurs sont régulièrement en position de hors-jeu.",
      "Les joueurs sont très régulièrement en position de hors-jeu.",
    ],
    counterAttacks: [
      "Et que l' équipe surprend très souvent ses adversaires en contre-attaques.",
      "Et que l' équipe surprend souvent ses adversaires en contre-attaques.",
      "ET que l' équipe surprend assez souvent ses adversaires en contre-attaques.",
      "Et que l' équipe surprend assez peu ses adversaires en contre-attaques.",
      "Et que l' équipe surprend peu ses adversaires en contre-attaques.",
      "Et que l' équipe surprend très peu ses adversaires en contre-attaques.",
    ],
  },
  DEFENSIF: {
    goals2: [
      "L‘ équipe encaisse très peu de buts",
      "L‘ équipe encaisse peu de buts",
      "L‘ équipe encaisse un peu trop de buts",
      "L‘ équipe encaisse beaucoup de buts",
      "L‘ équipe encaisse beaucoup trop de buts",
      "L‘ équipe encaisse énormément de buts",
    ],
    goalMean2: [
      "La régularité affiché tout au long de la saison est vraiment très positive !",
      "La régularité affiché tout au long de la saison est vraiment positive !",
      "La régularité affiché tout au long de la saison est légèrement positive !",
      "L'irrégularité affiché tout au long de la saison est assez inquiétante !",
      "L'irrégularité affiché tout au long de la saison est vraiment inquiétante !",
      "L'irrégularité affiché tout au long de la saison est vraiment très inquiétante !",
    ],
    cleanSheets2: [
      "son total de clean sheets est très avantageux.",
      "son total de clean sheets est avantageux.",
      "son total de clean sheets est assez favorable.",
      "son total de clean sheets n'est pas assez favorable.",
      "son total de clean sheets est pénalisant.",
      "son total de clean sheets est trop pénalisant.",
    ],
    headShotsRatio2: [
      "une très forte proportion de ces tirs sont des têtes.",
      "une forte proportion de ces tirs sont des têtes.",
      "une petite proportion de ces tirs sont des têtes.",
      "une assez faible proportion de ces tirs sont des têtes.",
      "une faible proportion de ces tirs sont des têtes.",
      "une très faible proportion de ces tirssont des têtes.",
    ],
    shotsFromBox2: [
      "les joueurs adverses se retrouvent très rarement dans des positions dangereuses.",
      "les joueurs adverses se retrouvent rarement dans des positions dangereuses.",
      "les joueurs adverses se retrouvent un peu trop souvent dans des positions dangereuses.",
      "les joueurs adverses se retrouvent assez souvent dans des positions dangereuses.",
      "les joueurs adverses se retrouvent trop souvent dans des positions dangereuses.",
      "les joueurs adverses se retrouvent beaucoup trop souvent dans des positions dangereuses.",
    ],
    crossesTotal2: [
      "En ce qui concerne les centres, l'équipe en subit très peu",
      "En ce qui concerne les centres, l'équipe en subit peu",
      "En ce qui concerne les centres, l'équipe en subit assez peu",
      "En ce qui concerne les centres, l'équipe en subit un peu trop",
      "En ce qui concerne les centres, l'équipe en subit beaucoup",
      "En ce qui concerne les centres, l'équipe en subit énormément",
    ],
    crossesSuccessful2: [
      "ils sont très peu dangereux pour l'arrière-garde.",
      "ils sont peu dangereux pour l'arrière-garde.",
      "ils sont assez peu dangereux pour l'arrière-garde.",
      "ils sont assez dangereux pour l'arrière-garde.",
      "ils sont souvent dangereux pour l'arrière-garde.",
      "ils sont très souvent dangereux pour l'arrière-garde.",
    ],
    crossesBlocked2: [
      "En proportion le nombre de centres intercepté est très favorable et met en évidence un manque important de repli des latéraux.",
      "En proportion le nombre de centres intercepté est favorable et met en évidence un manque important de repli des latéraux.",
      "En proportion le nombre de centres intercepté est légèrement favorable et met en évidence un manque important de repli des latéraux.",
      "En proportion le nombre de centres intercepté est assez faible et met en évidence un manque important de repli des latéraux.",
      "En proportion le nombre de centres intercepté est faible et met en évidence un manque important de repli des latéraux.",
      "En proportion le nombre de centres intercepté est trop faible et met en évidence un manque important de repli des latéraux.",
    ],
    counterAttacks2: [
      "À noter également que l’équipe se fait très rarement surprendre en contre-attaques.",
      "À noter également que l’équipe se fait rarement surprendre en contre-attaques.",
      "À noter également que l’équipe se fait peu surprendre en contre-attaques.",
      "À noter également que l’équipe se fait un peu trop surprendre en contre-attaques.",
      "À noter également que l’équipe se fait trop surprendre en contre-attaques.",
      "À noter également que l’équipe se fait beaucoup trop surprendre en contre-attaques.",
    ],
    shotBlocked2: [
      "Heureusement un nombre très favorable de tirs sont bloqués par les défenseurs.",
      "Heureusement un nombre favorable de tirs sont bloqués par les défenseurs.",
      "Heureusement un nombre assez favorable de tirs sont bloqués par les défenseurs.",
      "Malheureusement un nombre assez faible de tirs sont bloqués par les défenseurs.",
      "Malheureusement un nombre trop faible de tirs sont bloqués par les défenseurs.",
      "Malheureusement un nombre beaucoup trop faible de tirs sont bloqués par les défenseurs.",
    ],
    opponentOffsides2: [
      "L' alignement défensif est très performant, car les joueurs adverses sont très souvent pris au piège du hors-jeu.",
      "L' alignement défensif est performant, car les joueurs adverses sont souvent pris au piège du hors-jeu.",
      "L' alignement défensif est assez performant, car les joueurs adverses sont quelques fois pris au piège du hors-jeu.",
      "L' alignement défensif n'est pas assez performant, car les joueurs adverses ne sont pas suffisamment pris au piège du hors-jeu.",
      "L' alignement défensif n'est pas performant, car les joueurs adverses sont souvent pris au piège du hors-jeu.",
      "L' alignement défensif n'est du tout performant, car les joueurs adverses sont très souvent pris au piège du hors-jeu.",
    ],
    gkSaves2: [
      "Les analyses montrent que le ratio d'éfficacité du gardien est très rassurant.",
      "Les analyses montrent que le ratio d'éfficacité du gardien est rassurant.",
      "Les analyses montrent que le ratio d'éfficacité du gardien est assez rassurant.",
      "Les analyses montrent que le ratio d'éfficacité du gardien n'est pas assez rassurant.",
      "Les analyses montrent que le ratio d'éfficacité du gardien n'est pas rassurant.",
      "Les analyses montrent que le ratio d'éfficacité du gardien n'est pas très rassurant.",
    ],
    attacks: [
      "L' équipe ne subit que de très rares offensives",
      "L' équipe ne subit que de rares offensives",
      "L' équipe ne subit que peu offensives",
      "L' équipe subit un peu trop d'offensives",
      "L' équipe subit trop d'offensives",
      "L' équipe subit beaucoup trop d'offensives",
    ],
    withShots2: [
      "une grande majorité d'entre elles sont dangereuses.",
      "une majorité d'entre elles sont dangereuses.",
      "seulement une petite majorité d'entre elles sont dangereuses.",
      "seulement une grande minorité d'entre elles sont dangereuses.",
      "seulement une minorité d'entre elles sont dangereuses.",
      "seulement une petite minorité d'entre elles sont dangereuses.",
    ],
    shots2: [
      "En effet la fréquence des frappes est très faible",
      "En effet la fréquence des frappes est faible",
      "En effet la fréquence des frappes est faible",
      "En effet la fréquence des frappes est modérée",
      "En effet la fréquence des frappes est importante",
      "En effet la fréquence des frappes est très importante",
    ],
    corners2: [
      "Les adversaires comptabilisent très peu de corners",
      "Les adversaires comptabilisent peu de corners",
      "Les adversaires comptabilisent quelques corners",
      "Les adversaires comptabilisent trop de corners",
      "Les adversaires comptabilisent beaucoup de corners",
      "Les adversaires comptabilisent énormément de corners",
    ],
    cornersRatio2: [
      "ils ne représentent qu'un danger très faible pour la défense.",
      "ils ne représentent qu'un danger plutôt faible pour la défense.",
      "ils ne représentent qu'un danger assez faible pour la défense.",
      "ils représentent un réel danger pour la défense.",
      "ils représentent souvent un réel danger pour la défense.",
      "ils représentent très souvent un réel danger pour la défense.",
    ],
    freeKicksWithShot2: [
      "Ils subissent très peu de coups francs offensifs ",
      "Ils subissent peu de coups francs offensifs",
      "Ils subissent assez peu de coups francs offensifs",
      "Ils subissent trop de coups francs offensifs",
      "Ils subissent beaucoup de coups francs offensifs",
      "Ils subissent énormément de coups francs offensifs",
    ],
    freeKicksWithShotRatio2: [
      "heureusement le pourcentage de réussite est très faible.",
      "heureusement le pourcentage de réussite est faible.",
      "heureusement le pourcentage de réussite est assez faible.",
      "malheureusement le pourcentage de réussite n'est pas assez faible.",
      "malheureusement le pourcentage de réussite est élevé.",
      "malheureusement le pourcentage de réussite est très élevé.",
    ],
    groupPasses: [
      "Les espaces sont vraiment rares et empêchent très fortement les adversaires de développer un jeu de passes dangereux.",
      "Les espaces sont rares et empêchent fortement les adversaires de développer un jeu de passes dangereux.",
      "Les espaces sont assez rares et empêchent suffisamment les adversaires de développer un jeu de passes dangereux.",
      "Les espaces sont assez fréquent et n'empêchent pas suffisamment les adversaires de développer un jeu de passes dangereux.",
      "Les espaces sont fréquent et n'empêchent que faiblement les adversaires de développer un jeu de passes dangereux.",
      "Les espaces sont très fréquent et n'empêchent que trop faiblement les adversaires de développer un jeu de passes dangereux.",
    ],
  },
  DISTRIBUTION: {
    passes: [
      "Globalement l'équipe réalise un nombre de passes beaucoup plus important que ses adversaires",
      "Globalement l'équipe réalise un nombre de passes plus important que ses adversaires",
      "Globalement l'équipe réalise un nombre de passes un peu plus important que ses adversaires",
      "Globalement l'équipe réalise un nombre de passes un peu moins important que ses adversaires",
      "Globalement l'équipe réalise un nombre de passes moins important que ses adversaires",
      "Globalement l'équipe réalise un nombre de passes beaucoup moins important que ses adversaires",
    ],
    passesRatio: [
      "elles sont très souvent mieux ajustées.",
      "elles sont souvent mieux ajustées.",
      "elles sont légèrement mieux ajustées.",
      "elles sont un peu moins ajustées.",
      "elles sont moins ajustées.",
      "elles sont vraiment moins ajustées.",
    ],
    assists: [
      "Le nombre de passes décisives est le reflet de l'importante domination de l'équipe.",
      "Le nombre de passes décisives est le reflet de la domination de l'équipe.",
      "Le nombre de passes décisives est le reflet de la faible domination de l'équipe.",
      "Le nombre de passes décisives est le reflet des quelques difficultés de l'équipe.",
      "Le nombre de passes décisives est le reflet des difficultés de l'équipe.",
      "Le nombre de passes décisives est le reflet des grandes difficultés de l'équipe.",
    ],
    keyPasses: [
      "L’ animation offensive est performante, car l’équipe se crée un volume d’actions très élevé.",
      "L’ animation offensive est performante, car l’équipe se crée un volume d’actions élevé.",
      "L’ animation offensive est assez performante, car l’équipe se crée un volume d’actions suffisament élevé.",
      "L’ animation offensive n'est pas assez performante, car l’équipe se crée un volume d’actions limité.",
      "L’ animation offensive n'est vraiment pas performante, car l’équipe se crée un nombre d’actions trop limité.",
      "L’ animation offensive n'est absolument pas performante, car l’équipe se crée un nombre d’actions vraiment trop limité.",
    ],
    keyPassesRatio: [
      "Et l'efficacité est au rendez-vous car une très grande proportion de ces actions sont transformées en tirs.",
      "Et l'efficacité est au rendez-vous car une grande proportion de ces actions sont transformées en tirs.",
      "Et l'efficacité est limitée car une petite proportion de ces actions sont transformées en tirs.",
      "Et l’efficacité n’est pas au rendez-vous, car seulement une petite proportion de ces actions sont transformées en tirs.",
      "Et l’efficacité n’est pas au rendez-vous, car seulement une très petite proportion de ces actions sont transformées en tirs.",
      "Et l’efficacité n’est pas au rendez-vous, car seulement une infime proportion de ces actions sont transformées en tirs.",
    ],
    smartPasses: [
      "Les passes intélligentes et créatives sont omniprésentes dans le jeu de l'équipe.",
      "Les passes intélligentes et créatives sont présentes dans le jeu de l'équipe.",
      "Les passes intélligentes et créatives sont assez présentes dans le jeu de l'équipe.",
      "Les passes intélligentes et créatives sont assez peu présentes dans le jeu de l'équipe.",
      "Les passes intélligentes et créatives sont peu présentes dans le jeu de l'équipe.",
      "Les passes intélligentes et créavites sont rarissimes dans le jeu de l'équipe.",
    ],
    smartPassesRatio: [
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes est belle et bien présente dans l'effectif.",
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes est bien présente dans l'effectif.",
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes est suffisamment présente dans l'effectif.",
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes n'est pas suffisamment présente dans l'effectif.",
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes est peu présente dans l'effectif.",
      "La justesse technique nécessaire pour la bonne réalisation de ce type de gestes est absente de l'effectif.",
    ],
    throughPasses: [
      "Les mouvements dans la profondeur sont de très bonnes qualités et favorisent les passes en profondeurs.",
      "Les mouvements dans la profondeur sont de bonnes qualités et favorisent les passes en profondeurs.",
      "Les mouvements dans la profondeur sont d' assez bonnes qualités et favorisent quelques passes en profondeurs.",
      "Les mouvements dans la profondeur sont d' assez mauvaises qualités et ne favorisent pas suffisamment les passes en profondeurs.",
      "Les mouvements dans la profondeur sont de mauvaises qualités et ne favorisent pas les passes en profondeurs.",
      "Les mouvements dans la profondeur sont de très mauvaises qualités et ne favorisent pas les passes en profondeurs.",
    ],
    throughPassesRatio: [
      "Celles-ci sont vraiment précises et alimentent une très large proportion de ces appels.",
      "Celles-ci sont précises et alimentent une large proportion de ces appels de balles.",
      "Celles-ci sont assez précises et alimentent une légère proportion de ces appels de balles.",
      "Celles-ci ne sont pas assez précises et n'alimentent qu'une très petite proportion de ces appels de balles.",
      "Celles-ci ne sont pas précises et n'alimentent qu'une petite proportion de ces appels de balles.",
      "Celles-ci ne sont pas très précises et n'alimentent qu'une infime proportion de ces appels de balles.",
    ],
    crosses: [
      "L' équipe effectue énormément de centres,",
      "L' équipe effectue beaucoup de centres,",
      "L' équipe effectue assez de centres,",
      "L' équipe effectue assez peu de centres,",
      "L' équipe effectue peu de centres,",
      "L' équipe effectue très peu de centres,",
    ],
    crossesRatio: [
      "ils sont très précis et donc potentiellement prolifiques.",
      "ils sont précis et donc potentiellement prolifiques.",
      "ils sont assez précis et donc potentiellement prolifiques.",
      "ils sont assez imprécis et donc peu prolifiques.",
      "ils sont souvent imprécis et donc rarement prolifiques.",
      "ils sont trop souvent imprécis donc très rarement prolifiques.",
    ],
    passToFinalThirds: [
      "Une grande proportion de passes est effectuée dans le tiers offensif",
      "Une bonne proportion de passes est effectuée dans le tiers offensif",
      "Une faible proportion de passes est effectuée dans le tiers offensif",
      "Une petite proportion de passes est effectuée dans le tiers offensif",
      "Une très petite proportion de passes est effectuée dans le tiers offensif",
    ],
    passToFinalThirdsRatio: [
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est très satisfaisant.",
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est satisfaisant.",
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est assez moyen.",
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est assez bas.",
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est vraiment bas.",
      "dans une zone du terrain où elles doivent être fluides et rapides, le taux de réussite est vraiment trop bas.",
    ],
    shortLongRatio: [
      "Les passes longues sont très souvent utilisées",
      "Les passes longues sont souvent utilisées",
      "Les passes longues sont assez souvent utilisées",
      "Les passes longues sont assez peu utilisées",
      "Les passes longues sont rarement utilisées",
      "Les passes longues sont très rarement utilisées",
    ],
    longPassesRatio: [
      "le pourcentage de réussite qui en découle est très bon.",
      "le pourcentage de réussite qui en découle est bon.",
      "le pourcentage de réussite qui en découle est assez bon.",
      "le pourcentage de réussite qui en découle n'est pas assez bon.",
      "le pourcentage de réussite qui en découle n'est pas bon.",
      "le pourcentage de réussite qui en découle n'est vraiment pas bon.",
    ],
    passToPenaltyAreas: [
      "Les joueurs évoluant sur le front de l’attaque reçoivent régulièrement des ballons dans la surface de réparation adverse.",
      "Les joueurs évoluant sur le front de l’attaque reçoivent souvent des ballons dans la surface de réparation adverse.",
      "Les joueurs évoluant sur le front de l’attaque reçoivent assez souvent des ballons dans la surface de réparation adverse.",
      "Les joueurs évoluant sur le front de l’attaque ne reçoivent qu'assez peu de ballons dans la surface de réparation adverse.",
      "Les joueurs évoluant sur le front de l’attaque ne reçoivent que peu de ballons dans la surface de réparation adverse.",
      "Les joueurs évoluant sur le front de l’attaque ne reçoivent que très peu de ballons dans la surface de réparation adverse.",
    ],
    passToPenaltyAreasRatio: [
      "Le niveau de réussite des passes est largement à l'avantage de l'équipe, qui a ainsi l'occasion d'accroitre le danger.",
      "Le niveau de réussite des passes est à l'avantage de l'équipe, qui a ainsi l'occasion d'accroitre le danger.",
      "Le niveau de réussite des passes est légèrement à l'avantage de l'équipe, qui a ainsi l'occasion d'accroitre le danger.",
      "Le niveau de réussite des passes est légèrement défavorable à l'équipe, qui n'a pas suffisament d'occasion d'accroire le danger.",
      "Le niveau de réussite des passes est défavorable à l'équipe, qui a peu d'occasion d'accroire le danger.",
      "Le niveau de réussite des passes est défavorable à l'équipe, qui a très peu d'occasion d'accroire le danger.",
    ],
  },
  PERCUSSION: {
    dribbles: [
      "Les tentatives de dribbles sont très nombreuses",
      "Les tentatives de dribbles sont nombreuses",
      "Les tentatives de dribbles sont assez nombreuses",
      "Les tentatives de dribbles ne sont pas assez nombreuses",
      "Les tentatives de dribbles ne sont pas nombreuses",
      "Les tentatives de dribbles ne sont pas très nombreuses",
    ],
    dribblesRatio: [
      "le taux de réussite de ces dernières est très favorables. Ce ratio met en évidence l'excellente technique individuelle des protagonistes !",
      "le taux de réussite de ces dernières est favorables. Ce ratio met en évidence la qualité technique individuelle des protagonistes !",
      "le taux de réussite de ces dernières est assez favorable. Ce ratio  met en évidence la qualité technique individuelle de certains protagonistes !",
      "le taux de réussite de ces dernières n'est pas suffisamment favorable. Ce ratio met en évidence la qualité technique individuelle de certains protagonistes !",
      "le taux de réussite de ces dernières est défavorable. Ce ratio met en évidence le peu de qualité technique individuelle de certains protagonistes !",
      "le taux de réussite de ces dernières est défavorable. Ce ratio met en évidence le manque de qualité technique individuelle de certains protagonistes !",
    ],
    progressiveRun: [
      "Les courses en direction du but adverse sont très largement répétées.",
      "Les courses en direction du but adverse sont largement répétées.",
      "Les courses en direction du but adverse sont assez répétées.",
      "Les courses en direction du but adverse ne sont pas suffisamment répétée.",
      "Les courses en direction du but adverse sont rarement répétées.",
      "Les courses en direction du but adverse sont très rarement répétées.",
    ],
    progressivePasses: [
      "La proportion des passes réalisées dans la course des joueurs est très élevée.",
      "La proportion des passes réalisées dans la course des joueurs est élevée.",
      "La proportion des passes réalisées dans la course des joueurs est assez élevée.",
      "La proportion des passes réalisées dans la course des joueurs n’est pas assez élevée.",
      "La proportion des passes réalisées dans la course des joueurs est trop faible.",
      "La proportion des passes réalisées dans la course des joueurs est beaucoup trop faible.",
    ],
    progressivePassesRatio: [
      "Elles sont très souvent dans le bon tempo et favorisent ainsi l'avancée du bloc au plus près de la surface adverse.",
      "Elles sont souvent dans le bon tempo et favorisent ainsi l'avancée du bloc au plus près de la surface adverse.",
      "Elles sont suffisamment données dans le bon tempo et pour favoriser l'avancée du bloc au plus près de la surface adverse.",
      "Elles ne sont pas suffisamment données dans le bon tempo et ne favorisent donc pas l'avancée du bloc au plus près de la surface adverse.",
      "Elles sont rarement données dans le bon tempo et ne favorisent donc pas l'avancée du bloc au plus près de la surface adverse.",
      "Elles sont très rarement données dans le bon tempo et ne favorisent donc pas l'avancée du bloc au plus près de la surface adverse.",
    ],
  },
  RECOVERY: {
    losses: [
      "L' application des joueurs est mise en évidence car ils perdent vraiment moins de ballons que ses concurrents.",
      "L' application des joueurs est mise en évidence car ils perdent beaucoup moins de ballons que ses concurrents.",
      "L' application des joueurs est mise en évidence car ils perdent moins de ballons que ses concurrents.",
      "L' absence d'application des joueurs est mise en évidence car ils perdent plus de ballons que ses concurrents.",
      "L' absence d'application des joueurs est mise en évidence car ils perdent beaucoup plus de ballons que ses concurrents.",
      "L' absence d'application des joueurs est mise en évidence car ils perdent vraiment beaucoup plus de ballons que ses concurrents.",
    ],
    interceptions: [
      "Le taux d’interceptions est très élevé et révèle un sens du placement et d’anticipation très important des joueurs.",
      "Le taux d’interceptions est élevé et révèle un sens du placement et d’anticipation important des joueurs.",
      "Le taux d’interceptions est assez élevé et révèle un sens du placement et d’anticipation suffisant des joueurs.",
      "Le taux d’interceptions est assez faible et révèle un sens du placement et de l’anticipation inssufisant de la part des joueurs.",
      "Le taux d’interceptions est faible et révèle un sens du placement et de l’anticipation décevant de la part des joueurs.",
      "Le taux d’interceptions est très faible et révèle un sens du placement et de l’anticipation très décevant de la part des joueurs.",
    ],
    interceptionsOpponent: [
      "Comme évoqué dans la section distribution, les passes sont très précises rendant ainsi les interceptions adverses très compliquées.",
      "Comme évoqué dans la section distribution, les passes sont précises rendant ainsi les interceptions adverses compliquées.",
      "Comme évoqué dans la section distribution, les passes sont assez précises rendant ainsi les interceptions adverses un peu compliquées.",
      "Comme évoqué dans la section distribution, les passes sont assez imprécises  facilitant ainsi quelques interceptions adverses.",
      "Comme évoqué dans la section distribution, les passes sont imprécises favorisant ainsi les interceptions adverses.",
      "Comme évoqué dans la section distribution, les passes sont trop imprécises favorisant ainsi les interceptions adverses.",
    ],
    recoveries: [
      "L’ équipe montre une très grande efficacité dans la récupération du ballon et laisse par conséquent très peu d'espoir aux adversaires.",
      "L’ équipe montre une grande efficacité dans la récupération du ballon et laisse par conséquent peu d'espoir aux adversaires.",
      "L’ équipe montre une efficacité assez modérée dans la récupération du ballon et par conséquent de rares espoir aux adversaires.",
      "L’ équipe montre assez peu d'efficacité  dans la récupération du ballon et offre par conséquent des opportunités aux adversaires.",
      "L’ équipe montre peu d'efficacité dans la récupération du ballon et offre par conséquent trop d'opportunités aux adversaires.",
      "L’ équipe montre très peu d'efficacité dans la récupération du ballon et offre par conséquent beaucoup trop d'opportunités aux adversaires.",
    ],
    duels: [
      "Les joueurs multiplient très fortement le nombre de duels pour tenter de récupérer les ballons,",
      "Les joueurs multiplient fortement le nombre de duels pour tenter de récupérer les ballons,",
      "Les joueurs multiplient assez fortement le nombre de duels pour tenter de récupérer les ballons,",
      "Les joueurs ne multiplient pas assez le nombre de duels pour tenter de récupérer les ballons,",
      "Les joueurs ne multiplient pas beaucoup le nombre de duels pour tenter de récupérer les ballons,",
      "Les joueurs ne multiplient presque pas le nombre de duels pour tenter de récupérer les ballons,",
    ],
    duelsRatio: [
      "dans l'ensemble le niveau de réussite est vraiment favorable. En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
      "dans l'ensemble le niveau de réussite est favorable.En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
      "dans l'ensemble le niveau de réussite est assez favorable.En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
      "dans l'ensemble le niveau de réussite n'est pas suffisamment favorable. En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
      "dans l'ensemble le niveau de réussite est défavorable. En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
      "dans l'ensemble le niveau de réussite est vraiment défavorable. En étant plus précis dans l’analyse, nous identifions les points forts et les points faibles suivants :",
    ],
    defensiveDuelsRatio: [
      "- Une très grande majorité des duels défensifs sont gagnés par les joueurs",
      "- Une majorité des duels défensifs sont gagnés par les joueurs",
      "- Une petite majorité des duels défensifs sont gagnés par les joueurs",
      "- Une petite majorité des duels défensifs sont perdus par les joueurs",
      "- Une majorité des duels défensifs sont perdus par les joueurs",
      "- Une grande majorité des duels défensifs sont perdus par les joueurs",
    ],
    dribblesSuccessful: [
      "les tentatives de dribbles adverses sont très souvent avortées.",
      "les tentatives de dribbles adverses sont souvent avortées.",
      "les tentatives de dribbles adverses sont suffisamment avortées.",
      "les tentatives de dribbles adverses ne sont pas assez avortées.",
      "les tentatives de dribbles adverses sont rarement avortées.",
      "les tentatives de dribbles adverses sont très rarement avortées.",
    ],
    aerialDuelsRatio: [
      "- Le timming dans les duels aériens est excellent, car ils sont très souvent gagnés par l’équipe.",
      "- Le timming dans les duels aériens est bon, car ils sont souvent gagnés par l’équipe.",
      "- Le timming dans les duels aériens est tout juste acceptable, car ils ne sont que légèrement gagnés par l’équipe.",
      "- Le timming dans les duels aériens n'est pas assez bon, car ils sont légèrement gagnés par les adversaires.",
      "- Le timming dans les duels aériens est mauvais, car ils sont souvent gagnés par les adversaires.",
      "- Le timming dans les duels aériens est très mauvais, car ils sont très souvent gagnés par les adversaires.",
    ],
    slidingTacklesRatio: [
      "- Les tacles glissés sont bien maitrisés car très peu de fautes sont sifflées contre les protagonistes.",
      "- Les tacles glissés sont bien maitrisés car peu de fautes sont sifflées contre les protagonistes.",
      "- Les tacles glissés sont assez bien maitrisés car seulement quelques fautes sont sifflées contre les protagonistes.",
      "- Les tacles glissés sont assez mal maitrisés car quelques fautes sont sifflées contre les protagonistes.",
      "- Les tacles glissés sont mal maitrisés car trop de fautes sont sifflées contre les protagonistes.",
      "- Les tacles glissés sont très mal maitrisés car beaucoup trop de fautes sont sifflées contre les protagonistes.",
    ],
    groundDuelsRatio: [
      "- Les joueurs font preuve d’une très bonne agressivité et remportent un nombre très important de ballons dans les duels au sol.",
      "- Les joueurs font preuve d’une bonne agressivité et remportent un nombre important de ballons dans les duels au sol.",
      "- Les joueurs font preuve d’une agressivité suffisante et remportent un nombre assez élevé de ballons dans les duels au sol.",
      "- Les joueurs ne font pas preuve d’une agressivité suffisante et perdent trop de ballon dans les duels au sol.",
      "- Les joueurs font preuve d’un manque important d'agressivité et perdent beaucoup de ballon dans les duels au sol.",
      "- Les joueurs font preuve d’un manque très important d'agressivité et perdent beaucoup trop de ballon dans les duels au sol.",
    ],
    looseBallDuelsRatio: [
      "- Les joueurs font preuvent d'une très bonne réactivité et récupèrent un nombre signifiant de ballons.",
      "- Les joueurs font preuvent d'une bonne réactivité et récupèrent un nombre signifiant de ballons.",
      "- Les joueurs font preuvent d'une assez bonne réactivité et récupèrent quelques ballons.",
      "- Les joueurs ne font pas preuve d'une réactivité suffisante et ne écupèrent qu'un petit nombre de ballons.",
      "- Les joueurs manquent de réactivité pour pouvoir récupérer un nombre signifiant de ballons.",
      "- Les joueurs manquent terriblement de réactivité pour pouvoir récupérer un nombre très important de ballons.",
    ],
  },
  FREEKICKS: {
    cornersRatio: [
      "Les corners sont très bien négociés, car un très grand nombre d'entre eux aboutissent à une action dangereuse pour la défense adverse.",
      "Les corners sont bien négociés, car un nombre important d'entre eux aboutissent à une action dangereuse pour la défense adverse.",
      "Les corners sont moyennement bien négociés, car un nombre insuffisant d'entre eux aboutissent à une action dangereuse pour la défense adverse.",
      "Les corners sont mal négociés, car un petit nombre d'entre eux aboutissent à une action dangereuse pour la défense adverse.",
      "Les corners sont très mal négociés, car un trop petit nombre d'entre eux aboutissent à une action dangereuse pour la défense adverse.",
    ],
    freekicksRatio: [
      "Les opportunités de marquer sur coup francs indirect sont très importantes car ils sont très souvent cadrés.",
      "Les opportunités de marquer sur coup francs indirect sont importantes car ils sont très souvent cadrés.",
      "Les opportunités de marquer sur coup francs indirect sont modérée car ils ne sont pas suffisament cadrés.",
      "Les opportunités de marquer sur coup francs indirect sont très faible car ils sont rarement cadrés.",
      "Les opportunités de marquer sur coup francs indirect sont beaucoup trop faible car ils sont très rarement cadrés.",
    ],
    directFreeKicksRatio: [
      "Pour les coups francs directs, la performance des tireurs représentent un danger très sérieux pour le gardien adverse.",
      "Pour les coups francs directs, la performance des tireurs représentent un danger sérieux pour le gardien adverse.",
      "Pour les coups francs directs, la performance des tireurs représentent un danger modéré pour le gardien adverse.",
      "Pour les coups francs directs, la performance des tireurs ne représentent pas un danger important pour le gardien adverse.",
      "Pour les coups francs directs, la performance des tireurs ne représentent pas un danger très important pour le gardien adverse.",
    ],
    freeKicksWithShotRatio: [
      "Il y a une très grande majotié d'actions qui commencent par une phases de jeux arretés et qui se soldent par un tirs.",
      "Il y a une grande majotié d'actions qui commencent par une phases de jeux arretés et qui se soldent par un tirs.",
      "Il y a une petite majotié d'actions qui commencent par une phases de jeux arretés et qui se soldent par un tirs.",
      "Il y a peu d'actions qui commencent par une phases de jeux arretés et qui se soldent par un tirs.",
      "Il y a très peu d'actions qui commencent par une phases de jeux arretés et qui se soldent par un tirs.",
    ],
  },
  PRESSING: {
    ppda: [
      "L' équipe est très agressive sur le porteur du ballon, elle cherche une récupération haute sur le terrain en coupant très rapidement les transitions adverses.",
      "L' équipe est agressive sur le porteur du ballon, elle cherche une récupération haute sur le terrain en coupant rapidement les transitions adverses.",
      "L’ équipe est suffisamment agressive sur le porteur du ballon, elle cherche une récupération assez haute sur le terrain en coupant aussi vite que possible les transitions adverses.",
      "L’ équipe ne montre pas suffisamment d’agressivité sur le porteur du ballon, elle ne peut espérer qu’une récupération assez basse sur le terrain, car les adversaires ont un peu de temps pour progresser vers la surface.",
      "L’ équipe ne montre pas beaucoup agressivité sur le porteur du ballon, elle ne peut espérer qu’une récupération basse sur le terrain, car les adversaires ont le temps de temps pour progresser vers la surface.",
      "L’ équipe ne montre quasiment pas agressivité sur le porteur du ballon, elle ne peut espérer qu’une récupération trop basse sur le terrain, car les adversaires ont énormément de temps pour progresser vers la surface.",
    ],
    challengeIntensity: [
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est très élevé.",
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est élevé.",
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est assez élevé.",
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est assez faible.",
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est faible.",
      "Le nombre d'actions défensives que l'équipe réalise pour récupérer le ballon est très faible.",
    ],
  },
  POSSESSION: {
    groupPossession: [
      "Lorsqu'elle est en possession du ballon et doit faire le jeu, son ratio de productivité est vraiment favorable. Elle impose fortement son style de jeu tout en maitrisant parfaitement ses concurrents.",
      "Lorsqu'elle est en possession du ballon et doit faire le jeu, son ratio de productivité est favorable. Elle impose fortement son style de jeu tout en maitrisant parfaitement ses concurrents. ",
      "Lorsqu'elle est en possession du ballon et doit faire le jeu, son ratio de productivité est assez favorable. Elle impose timidement son style de jeu tout en maitrisant légèrement ses concurrents.",
      "Lorsqu'elle est en possession du ballon et doit faire le jeu, son ratio de productivité n’est pas suffisamment favorable. Elle impose assez rarement son style de jeu et laisse un peu trop de possibilités à ses concurrents.",
      "Lorsqu'elle est en possession du ballon et doit faire le jeu, son ratio de productivité est mauvais. Elle impose rarement son style de jeu et laisse trop de possibilités à ses concurrents. ",
      "Lorsqu'Elle est en possession du ballon et doit faire le jeu, son ratio de productivité est trop mauvais. Elle impose très rarement son style de jeu et laisse beaucoup trop de possibilités à ses concurrents.",
    ],
    groupOpponentPossession: [
      "Quand elle n’a pas le ballon, elle n’en est pas moins hyper compétitive. Son organisation et jeu sans ballon lui confère une très bonne solidité défensive, mais aussi une redoutable efficacité offensive.",
      "Quand elle n’a pas le ballon, elle n’en est pas moins compétitive. Son organisation et jeu sans ballon lui confère une  bonne solidité défensive, mais aussi une efficacité offensive favorable.",
      "Quand elle n’a pas le ballon, elle reste assez compétitive. Son organisation et jeu sans ballon lui confère une assez bonne solidité défensive, mais aussi une efficacité offensive suffisante.",
      "Quand elle n’a pas le ballon, elle n'est pas suffisamment compétitive. Son organisation et jeu sans ballon lui confère une petite fragilité défensive, mais aussi une efficacité offensive insuffisante.",
      "Quand elle n’a pas le ballon, elle est rarement compétitive. Son organisation et jeu sans ballon lui confère une grande fragilité défensive, mais aussi une efficacité offensive trop faible.",
      "Quand elle n’a pas le ballon, elle est rarement compétitive. Son organisation et jeu sans ballon lui confère une très grande fragilité défensive, mais aussi une efficacité offensive beaucoup trop faible.",
    ],
  },
};

export const TPI_TRANSLATION: any = {
  OFFENSIF: {
    Goals: "Buts",
    withShots: "Attaques",
    Shots: "Tirs",
    headShotsRatio: "Jeu Aérien",
    Offsides: "Hors-Jeu",
  },
  DEFENSIF: {
    goals2: "Buts",
    groupPasses: "Passes",
    attacks: "Actions",
    corners2: "Coups de Pieds Arrêtés",
    opponentOffsides2: "Hors-Jeu",
    gkSaves2: "Gardien",
  },
  DISTRIBUTION: {
    passes: "Passes",
    passToFinalThirds: "Passes dans le tiers offensif",
    keyPasses: "Passes Clefs",
    throughPasses: "Passes en Profondeur",
    smartPasses: "Passes Créatives",
    crosses: "Centres",
    passToPenaltyAreas: "Passes dans la surface de réparation",
    assists: "Passes Décisives",
  },
  PERCUSSION: {
    dribbles: "Dribbles",
    progressiveRun: "Accélérations",
    progressivePasses: "Passes dans la course",
  },
  RECOVERY: {
    losses: "Pertes de Balles",
    interceptions: "Interceptions",
    recoveries: "Récupération",
    duels: "Duels",
  },
  PRESSING: {
    ppda: "Intensité du Pressing",
  },
  FREEKICKS: {
    cornersRatio: "Corners",
    freekicksRatio: "Coups Franc",
  },
  POSSESSION: {
    groupPossession: "Possession",
    groupOpponentPossession: "Possession adverse",
  },
};
