export const TPI_CATEGORY_LABEL: any = {
  OFFENSIF: "OFFENSIVE",
  DEFENSIF: "DEFENSIVE",
  DISTRIBUTION: "DISTRIBUTION",
  PERCUSSION: "PERCUSSION",
  RECOVERY: "REGAIN POSSESSION",
  PRESSING: "PRESSING",
  FREEKICKS: "SET PIECES",
  POSSESSION: "GAME SET",
};

export const TPI_ORDER_CHART: any = {
  OFFENSIF: "OFFENSIVE",
  DEFENSIF: "DEFENSIVE",
  DISTRIBUTION: "DISTRIBUTION",
  PERCUSSION: "PERCUSSION",
  RECOVERY: "REGAIN POSSESSION",
  PRESSING: "PRESSING",
  FREEKICKS: "SET PIECES",
  POSSESSION: "GAME SET",
};

export const TPI_SUMMARY: any = {
  OFFENSIF: [
    "L’équipe affiche des statistiques offensives trop faibles pour espérer mettre en danger ses adversaires et gagner les matchs.",
    "L’équipe affiche des statistiques offensives faibles pour espérer mettre en danger ses adversaires et gagner les matchs.",
    "L’équipe affiche des statistiques offensives moyenne lui permettant de mettre en danger ses adversaires et gagner les matchs.",
    "L’équipe affiche des statistiques offensives fortes qui lui permettent de mettre en danger ses adversaires et gagner les matchs.",
    "L’équipe affiche des statistiques offensives très fortes qui lui permettent de mettre en danger ses adversaires et gagner les matchs.",
  ],
  DEFENSIF: [
    "Le niveau défensif affiché par l’équipe est très inquiétant, car les adversaires se créent beaucoup trop d’occasions.",
    "Le niveau défensif affiché par l’équipe est inquiétant, car les adversaires se créent trop d’occasions.",
    "Le niveau défensif affiché par l’équipe est moyen, car les adversaires arrivent à se créer quelques occasions.",
    "Le niveau défensif affiché par l’équipe est rassurant, car les adversaires ne se créent que peu d’occasions.",
    "LLe niveau défensif affiché par l’équipe est très rassurant, car les adversaires ne se créent que très peu d’occasions.",
  ],
  DISTRIBUTION: [
    "Le jeu de passes n’est pas suffisamment performant pour qu’il permette à l’équipe de mettre en danger ses adversaires.",
    "Le jeu de passes n’est pas assez performant pour qu’il permette à l’équipe de mettre en danger ses adversaires.",
    "Le jeu de passes manque de régularité dans la performance pour qu’il permette à l’équipe de mettre plus souvent ses adversaires en danger.",
    "Le jeu de passes est assez performant pour qu’il permette à l’équipe de mettre en danger ses adversaires.",
    "Le jeu de passes est suffisamment performant pour qu’il permette à l’équipe de mettre en danger ses adversaires.",
  ],
  PERCUSSION: [
    "Le jeu de percussion de l’équipe est extrêmement faible, car elle n’arrive pas à se créer des brèches par la vitesse et les dribbles de ses joueurs.",
    "Le jeu de percussion de l’équipe est trop faible, car elle n’arrive pas à se créer des brèches par la vitesse et les dribbles de ses joueurs.",
    "Le jeu de percussion de l’équipe est faible, car elle n’arrive pas à se créer des brèches par la vitesse et les dribbles de ses joueurs.",
    "Le jeu de percussion de l’équipe est fort, car elle arrive à se créer des brèches par la vitesse et les dribbles de ses joueurs.",
    "Le jeu de percussion de l’équipe est extrêmement fort, car elle arrive à se créer des brèches par la vitesse et les dribbles de ses joueurs.",
  ],
  RECOVERY: [
    "L’équipe montre un ratio de récupération très faible par rapport au nombre de ballons qu’elle perd au profit de ses adversaires.",
    "L’équipe montre un ratio de récupération faible par rapport au nombre de ballons qu’elle perd au profit de ses adversaires.",
    "L’équipe montre un ratio de récupération modéré par rapport au nombre de ballons qu’elle perd au profit de ses adversaires.",
    "L’équipe montre un ratio de récupération performant par rapport au nombre de ballons qu’elle perd au profit de ses adversaires.",
    "L’équipe montre un ratio de récupération très performant par rapport au nombre de ballons qu’elle perd au profit de ses adversaires.",
  ],
  PRESSING: [
    "L’équipe perd un nombre de ballons beaucoup trop élevé et elle se met par conséquent trop facilement en danger.",
    "L’équipe perd un nombre de ballons trop élevé et elle se met par conséquent trop facilement en danger.",
    "L’équipe perd un nombre de ballons élevé et elle se met par conséquent trop facilement en danger.",
    "L’équipe perd peu de ballons au profit d’une construction du jeu dangereuse pour les adversaires.",
    "L’équipe perd très peu de ballons au profit d’une construction du jeu plus dangereux pour les adversaires.",
  ],
  FREEKICKS: [
    "Comme l’équipe domine très rarement le jeu, les adversaires commettent moins de fautes et elle bénéficie donc d’un très faible pourcentage de possibilité sur coups de pied arrêtés.",
    "Comme l’équipe domine rarement le jeu, les adversaires commettent moins de fautes et elle bénéficie donc d’un faible pourcentage de possibilité sur coups de pied arrêtés.",
    "Comme l’équipe domine le jeu par intermittence, les adversaires commettent quelques fautes et elle bénéficie donc d’un pourcentage modéré de possibilité sur coups de pied arrêtés.",
    "Comme l’équipe domine le jeu très régulièrement, les adversaires commettent plus de fautes et elle bénéficie donc d’un pourcentage important de possibilité sur coups de pied arrêtés.",
    "Comme l’équipe domine le jeu fortement, les adversaires commettent plus de fautes et elle bénéficie donc d’un pourcentage très important de possibilité sur coups de pied arrêtés.",
  ],
  POSSESSION: [
    "La possession du ballon est très fortement à l’avantage des adversaires qui contrôlent le jeu et qui sont par conséquent plus souvent dangereux.",
    "La possession du ballon est fortement à l’avantage des adversaires qui contrôlent le jeu et qui sont par conséquent plus souvent dangereux.",
    "La possession du ballon est légèrement à l’avantage des adversaires qui contrôlent le jeu et qui sont par conséquent plus souvent dangereux.",
    "La possession du ballon est à l’avantage de l’équipe qui contrôle le jeu et qui est par conséquent plus souvent dangereuse.",
    "La possession du ballon est fortement à l’avantage de l’équipe qui contrôle le jeu et qui est par conséquent plus souvent dangereuse.",
  ],
};

export const TPI: any = {
  OFFENSIF: {
    goals: [
      "Le nombre de buts inscrit est très insuffisant.",
      "Le nombre de buts inscrit est insuffisant.",
      "Le nombre de buts inscrit est dans la moyenne des équipes.",
      "Le nombre de buts inscrit est élevé.",
      "Le nombre de buts inscrit est très élevé.",
    ],
    goalConversion: [
      "L’efficacité devant la cage est un point tres faible !",
      "L’efficacité devant la cages est un point faible! ",
      "L’efficacité devant la cages est moyennement présente!",
      "L’efficacité devant la cages est au rendez-vous !",
      "L’efficacité devant la cages est redoutable!",
    ],
    cleanSheets: [
      "Le total des clean sheet adverse, confirme les très mauvaises statistiques offensives de l’équipe.",
      "Le total des clean sheet adverse, confirme les mauvaises statistiques offensives de l’équipe.",
      "Le total des clean sheet adverse, confirme les statistiques offensives mitigées de l’équipe.",
      "Le total des clean sheet adverse, confirme les bonnes statistiques offensives de l’équipe.",
      "Le total des clean sheet adverse, confirme les excellentes statistiques offensives de l’équipe.",
    ],
    shots: [
      "La moyenne des tirs par match est très faible.",
      "La moyenne des tirs par match est faible.",
      "La moyenne des tirs par match est mitigée.",
      "La moyenne des tirs par match est élevée.",
      "La moyenne des tirs par match est très élevée.",
    ],
    shotsRatio: [
      "Et le ratio de précision qui en découle est extrêmement décevant !",
      "Et le ratio de précision qui en découle est décevant !  ",
      "Et le ratio de précision qui en découle est insuffisant !",
      "Et le ratio de précision qui en découle est satisfaisant !",
      "Et le ratio de précision qui en découle est vraiment satisfaisant !",
    ],
    shotsOutsideBox: [
      "Les joueurs tentent très peu de frappes lointaines.",
      "Les joueurs tentent peu de frappes lointaines.",
      "Les joueurs tentent quelques frappes lointaines.",
      "Les joueurs tentent souvent des frappes lointaines.",
      "Les joueurs tentent très souvent des frappes lointaines.",
    ],
    shotsOutsideConfidence: [
      "Pour un taux de réussite extrêmement pénalisant !",
      "Pour un taux de réussite vraiment pénalisant !",
      "Pour un taux de réussite moyennement élevé !",
      "Pour un taux de réussite satisfaisant !",
      "Pour un taux de réussite très satisfaisant !",
    ],
    shotFromBox: [
      "L’équipe se met trop rarement dans les meilleures positions de tir.",
      "L’équipe se met rarement dans les meilleures positions de tir.",
      "L’équipe se met parfois dans les meilleures positions de tir.",
      "L’équipe se met fréquemment dans les meilleures positions de tir.",
      "L’équipe se met très fréquemment dans les meilleures positions de tir.",
    ],
    shotFromBoxRatio: [
      "L’équipe se met trop rarement dans les meilleures positions de tir.",
      "L’équipe se met rarement dans les meilleures positions de tir.",
      "L’équipe se met parfois dans les meilleures positions de tir.",
      "L’équipe se met fréquemment dans les meilleures positions de tir.",
      "L’équipe se met très fréquemment dans les meilleures positions de tir.",
    ],
    headShots: [
      "Le jeu aérien est très rarement utilisé.",
      "Le jeu aérien est rarement utilisé.",
      "Le jeu aérien pourrait être plus utilisé.",
      "Le jeu aérien est souvent utilisé.",
      "Le jeu aérien est très souvent utilisé.",
    ],
    headShotsRatio: [
      "Pour un taux de tête cadré très largement en dessous des attentes !",
      "Pour un taux de tête cadré largement en dessous des attentes !",
      "Pour un taux de tête cadré légèrement en dessus des attentes !",
      "Pour un taux de tête cadré au-dessus des attentes !",
      "Pour un taux de tête cadré largement au-dessus des attentes !",
    ],
  },
  DEFENSIF: {
    goals: [
      "L’équipe encaisse beaucoup trop de buts.",
      "L’équipe encaisse trop de buts.",
      "L’équipe encaisse un nombre de buts important.",
      "L’équipe encaisse peu de buts.",
      "L’équipe encaisse très peu de buts.",
    ],
    cleanSheets: [
      "Pour un total de clean sheets très médiocre, comme le niveau défensif !",
      "Pour un total de clean sheets médiocre, comme le niveau défensif !",
      "Pour un total de clean sheets moyen, comme le niveau défensif !",
      "Pour un total de clean sheets élevé, comme le niveau défensif !",
      "Pour un total de clean sheets très élevé, comme le niveau défensif!",
    ],
    shots: [
      "Les adversaires comptabilisent beaucoup trop de frappes à leur compteur. ",
      "Les adversaires comptabilisent trop de frappes à leur compteur. ",
      "Les adversaires comptabilisent quelques frappes à leur compteur. ",
      "Les adversaires comptabilisent peu de frappes à leur compteur. ",
      "Les adversaires comptabilisent très peu de frappes à leur compteur. ",
    ],
    headShotsRatio: [
      "Avec une très forte proportion de tête ! ",
      "Avec une forte proportion de tête !",
      "Avec une proportion modérée de tête !",
      "Avec une faible proportion de tête !",
      "Avec une très faible proportion de tête !",
    ],
    crossesTotal: [
      "Les équipes adverses exploitent trop facilement la largeur du terrain pour finaliser leurs attaques par des centres. ",
      "Les équipes adverses exploitent facilement la largeur du terrain pour finaliser leurs attaques par des centres.",
      "Les équipes adverses exploitent moyennement la largeur du terrain pour finaliser leurs attaques par des centres.",
      "Les équipes adverses exploitent difficilement la largeur du terrain pour finaliser leurs attaques par des centres.",
      "Les équipes adverses exploitent très difficilement la largeur du terrain pour finaliser leurs attaques par des centres.",
    ],
    crossesSuccessful: [
      "Avec un ratio de réussite très pénalisant pour la défense !",
      "Avec un ratio de réussite pénalisant pour la défense !",
      "Avec un ratio de réussite moyennement valorisant pour la défense !",
      "Avec un ratio de réussite valorisant pour la défense!",
      "Avec un ratio de réussite très valorisant pour la défense ! ",
    ],
    crossesBlocked: [
      "Le ratio de centre intercepté est trop faible et montre un repli beaucoup trop laxiste des latéraux.",
      "Le ratio de centre intercepté est faible et montre un repli trop laxiste des latéraux.",
      "Le ratio de centre intercepté est modéré et montre un repli par intermittence des latéraux.",
      "Le ratio de centre intercepté est favorable et montre un repli rigoureux des latéraux.",
      "Le ratio de centre intercepté est très favorable et montre un repli rigoureux des latéraux.",
    ],
    shotFromBox: [
      "L’aisance qu’ont les adversaires pour se mettre dans les meilleures dispositions de tirs est très alarmante.",
      "L’aisance qu’ont les adversaires pour se mettre dans les meilleures dispositions de tirs est alarmante.",
      "Les adversaires savent profiter des errements défensifs pour se mettre dans les meilleures dispositions de tirs.",
      "La difficulté qu’ont les adversaires pour se mettre dans les meilleures dispositions de tirs est rassurante.",
      "La difficulté qu’ont les adversaires pour se mettre dans les meilleures dispositions de tirs est très rassurante.",
    ],
    shotsBlocked: [
      "Le niveau défensif est également mis en évidence par le volume d’intervention beaucoup trop faible des défenseurs pour contrer les frappes adverses.",
      "Le niveau défensif est également mis en évidence par le volume d’intervention trop faible des défenseurs pour contrer les frappes adverses.",
      "Le niveau défensif est également mis en évidence par le volume d’intervention mitigé des défenseurs pour contrer les frappes adverses.",
      "Le niveau défensif est également mis en évidence par le volume d’intervention élevé des défenseurs pour contrer les frappes adverses.",
      "Le niveau défensif est également mis en évidence par le volume d’intervention très élevé des défenseurs pour contrer les frappes adverses.",
    ],
    counterAttacks: [
      "L’équipe se laisse beaucoup trop surprendre en contre-attaque.",
      "L’équipe se laisse trop surprendre en contre-attaque.",
      "L’équipe se laisse quelquefois surprendre en contre-attaque.",
      "L’équipe se laisse rarement surprendre par des contre-attaques.",
      "L’équipe se laisse très rarement surprendre par des contre-attaques.",
    ],
    opponentOffsides: [
      "Le ratio de hors-jeux sifflés par rapport au nombre de tirs subis met en évidence un alignement défensif trop pénalisant.",
      "Le ratio de hors-jeux sifflés par rapport au nombre de tirs subis met en évidence un alignement défensif pénalisant.",
      "Le ratio de hors-jeux sifflés par rapport au nombre de tirs subis met en évidence un alignement défensif approximatif.",
      "Le ratio de hors-jeux sifflés par rapport au nombre de tirs subis met en évidence un alignement défensif avantageux.",
      "Le ratio de hors-jeux sifflés par rapport au nombre de tirs subis met en évidence un alignement défensif très avantageux.",
    ],
    gkSaves: [
      "Très peu aidé par sa défense, le gardien est beaucoup trop sollicité.",
      "Peu aidé par sa défense, le gardien est beaucoup trop sollicité.",
      "Moyennement aidé par sa défense, le gardien est parfois sollicité.",
      "Bien aidé par la solidité du bloc équipe, le gardien est peu sollicité.",
      "Bien aidé par la solidité du bloc équipe, le gardien est très peu sollicité.",
    ],
  },
  DISTRIBUTION: {
    passes: [
      "Le nombre de passes est beaucoup plus faible que celui des adversaires.",
      "Le nombre de passes est plus faible que celui des adversaires.",
      "Le nombre de passes est aussi élevé que celui des adversaires.",
      "Le nombre de passes est plus élevé que celui des adversaires.",
      "Le nombre de passes est beaucoup plus élevé que celui des adversaires.",
    ],
    passesRatio: [
      "Pour un taux de précision qui est vraiment trop bas ! ",
      "Pour un taux de précision qui est trop bas ! ",
      "Pour un taux de précision qui est modéré ! ",
      "Pour un taux de précision qui est très élevé ! ",
      "Pour un taux de précision qui est vraiment très élevé ! ",
    ],
    assists: [
      "Le nombre de passes décisives est révélateur de la trop faible influence de l’équipe sur les rencontres.",
      "Le nombre de passes décisives est révélateur de la faible influence de l’équipe sur les rencontres.",
      "Le nombre de passes décisives est révélateur de l’influence modérée de l’équipe sur les rencontres.",
      "Le nombre de passes décisives est révélateur de la forte influence de l’équipe sur les rencontres.",
      "Le nombre de passes décisives est révélateur de la très forte influence de l’équipe sur les rencontres.",
    ],
    keyPasses: [
      "Le nombre de passes « dites clefs » qui permet à l’équipe de se créer des opportunités de marquer est trop faible.",
      "Le nombre de passes « dites clefs » qui permet à l’équipe de se créer des opportunités de marquer est faible.",
      "Le nombre de passes « dites clefs » qui permet à l’équipe de se créer des opportunités de marquer est modéré.",
      "Le nombre de passes « dites clefs » qui permet à l’équipe de se créer des opportunités de marquer est important.",
      "Le nombre de passes « dites clefs » qui permet à l’équipe de se créer des opportunités de marquer est très élevé.",
    ],
    shotAssists: [
      "Pour un niveau d’imprécision très pénalisant ! ",
      "Pour un niveau d’imprécision pénalisant ! ",
      "Pour un niveau de précision moyennement élevé  ! ",
      "Pour un niveau précision favorable ! ",
      "Pour un niveau de précision très favorable ! ",
    ],
    smartPasses: [
      "Les passes techniques et créatives en profondeur ou dans le dos de la défense sont trop rares dans le jeu.",
      "Les passes techniques et créatives en profondeur ou dans le dos de la défense sont peu présentes dans le jeu.",
      "Les passes techniques et créatives en profondeur ou dans le dos de la défense sont moyennement présentes dans le jeu.",
      "Les passes techniques et créatives en profondeur ou dans le dos de la défense sont présentes dans le jeu.",
      "Les passes techniques et créatives en profondeur ou dans le dos de la défense sont très présentes dans le jeu.",
    ],
    smartPassesRatio: [
      "Pour une justesse technique qui fait fortement défaut !",
      "Pour une justesse technique qui fait défaut !",
      "Pour une justesse technique modérément favorable !",
      "Pour une justesse technique fortement favorable !",
      "Pour une justesse technique redoutable !",
    ],
    crosses: [
      "L’équipe réalise très peu de centres pour apporter le danger dans la surface de réparation.",
      "L’équipe réalise peu de centres pour apporter le danger dans la surface de réparation.",
      "L’équipe réalise quelques centres pour apporter le danger dans la surface de réparation.,",
      "L’équipe réalise beaucoup de centres pour apporter le danger dans la surface de réparation.",
      "L’équipe réalise énormément de centres pour apporter le danger dans la surface de réparation.",
    ],
    crossesRatio: [
      "Pour un résultat trop souvent inoffensif ! ",
      "Pour un résultat souvent inoffensif ! ",
      "Pour un résultat moyennement dangereux ! ",
      "Pour un résultat souvent dangereux ! ",
      "Pour un résultat très souvent dangereux !",
    ],
    longPassesRatio: [
      "Le jeu long est très mal maitrisé, les approximations sont trop fréquentes pour qu’il puisse être une arme offensive de l’équipe.",
      "Le jeu long est mal maitrisé, les approximations sont trop fréquentes pour qu’il puisse être une arme offensive de l’équipe. ",
      "Le jeu long est mal moyennement maitrisé, il peut parfois être une arme offensive supplémentaire pour mener à bien les actions.",
      "Le jeu long est très bien maitrisé, il est une arme offensive supplémentaire pour mener à bien les actions.",
      "Le jeu long est très bien maitrisé, il est une arme offensive supplémentaire pour mener à bien les actions.",
    ],
    passToPenaltyAreas: [
      "Le volume de passes dans la surface adverse montre un très faible niveau de dangerosité de l’équipe.",
      "Le volume de passes dans la surface adverse montre un faible niveau de dangerosité de l’équipe.",
      "Le volume de passes dans la surface adverse montre un niveau de dangerosité modéré de l’équipe.",
      "Le volume de passes dans la surface adverse montre un niveau de dangerosité important de l’équipe.",
      "Le volume de passes dans la surface adverse montre un niveau de dangerosité très important de l’équipe.",
    ],
  },
  PERCUSSION: {
    dribbles: [
      "Les tentatives de dribbles sont très insuffisantes pour ce niveau de compétition.",
      "Les tentatives de dribbles sont insuffisantes pour ce niveau de compétition.",
      "Les tentatives de dribbles sont peu nombreuses pour ce niveau de compétition.",
      "Les tentatives de dribbles sont nombreuses pour ce niveau de compétition.",
      "Les tentatives de dribbles sont très nombreuses pour ce niveau de compétition.",
    ],
    dribblesRatio: [
      "Pour un ratio de réussite très insuffisant ! ",
      "Pour un ratio de réussite insuffisant ! ",
      "Pour un ratio de réussite modéré ! ",
      "Pour un ratio de réussite satisfaisant ! ",
      "Pour un ratio de réussite très satisfaisant ! ",
    ],
    progressiveRunRatio: [
      "Le pourcentage d’accélérations vers le but adverse n’est pas suffisamment élevé.",
      "Le pourcentage d’accélérations vers le but adverse n’est pas assez élevé.",
      "Le pourcentage d’accélérations vers le but adverse est moyennement élevé.",
      "Le pourcentage d’accélérations vers le but adverse est élevé.",
      "Le pourcentage d’accélérations vers le but adverse est très élevé.",
    ],
    progressivePasses: [
      "Le volume de passes progressives est trop limité dans le jeu de l’équipe, qui manque par conséquent de mouvement vers l’avant.",
      "Le volume de passes progressives est limité dans le jeu de l’équipe, qui manque par conséquent de mouvement vers l’avant.",
      "Le volume de passes progressives est moyennement utilisé dans le jeu de l’équipe, qui manque par conséquent de mouvement vers l’avant.",
      "Le volume de passes progressives est satisfaisant dans le jeu de l’équipe, qui effectue par conséquent beaucoup de mouvement vers l’avant.",
      "Le volume de passes progressives est très satisfaisant dans le jeu de l’équipe, qui effectue par conséquent beaucoup de mouvement vers l’avant.",
    ],
    progressivePassesRatio: [
      "Et la justesse technique très insatisfaisante ! ",
      "Et la justesse technique insatisfaisante ! ",
      "Et la justesse technique moyennement élevé ! ",
      "Et la justesse technique élevé ! ",
      "Et la justesse technique très élevé ! ",
    ],
  },
  RECOVERY: {
    losses: [
      "Les pertes de balle sont beaucoup trop nombreuses.",
      "Les pertes de balle sont trop nombreuses.",
      "Les pertes de balle sont modérées.",
      "Les pertes de balle sont peu nombreuses.",
      "Les pertes de balle sont très peu nombreuses.",
    ],
    lossesRatioField: [
      "Pour un ratio de perte dangereuse plutôt élevé ! ",
      "Pour un ratio de perte dangereuse élevé ! ",
      "Pour un ratio de perte dangereuse modéré ! ",
      "Pour un ratio de perte dangereuse plutôt faible ! ",
      "Pour un ratio de perte dangereuse très faible !",
    ],
    interceptions: [
      "Le taux d’interceptions est très faible et révèle un sens du placement et de l’anticipation décevant de la part des joueurs.",
      "Le taux d’interceptions est faible et révèle un sens du placement et de l’anticipation décevant de la part des joueurs.",
      "Le taux d’interceptions est modéré et révèle un sens du placement et de l’anticipation par intermittences de la part des joueurs.",
      "Le taux d’interceptions est élevé et révèle un sens du placement et d’anticipation important de la part des joueurs.",
      "Le taux d’interceptions est très élevé et révèle un sens du placement et d’anticipation important de la part des joueurs.",
    ],
    interceptionsOpponent: [
      "Le manque de mouvement des joueurs et d’application dans les passes fait que les adversaires interceptent beaucoup trop de ballons.",
      "Le manque de mouvement des joueurs et d’application dans les passes fait que les adversaires interceptent trop de ballons.",
      "Le jeu en mouvement des joueurs et l’application dans les passes limitent moyennement les interceptions adverses du ballon.",
      "Le jeu en mouvement des joueurs et l’application dans les passes limitent les interceptions adverses du ballon.",
      "Le jeu en mouvement des joueurs et l’application dans les passes limitent fortement les interceptions adverses du ballon.",
    ],
    recoveries: [
      "l’équipe montre de très grosses faiblesses dans la récupération du ballon et laisse par conséquent une très forte possession aux adversaires",
      "l’équipe montre de grosses faiblesses dans la récupération du ballon et laisse par conséquent une forte possession aux adversaires",
      "L’équipe montre une efficacité modérée dans la récupération du ballon et se partage la possession avec les adversaires.",
      "L’équipe montre une grande efficacité dans la récupération du ballon et laisse par conséquent une faible possession aux adversaires.",
      "L’équipe montre une très grande efficacité dans la récupération du ballon et laisse par conséquent une très faible possession aux adversaires.",
    ],
    recoveriesRatioField: [
      "Le ratio de récupération adverse dite dangereuse est beaucoup trop important.",
      "Le ratio de récupération adverse dite dangereuse est trop important.",
      "Le ratio de récupération adverse dite dangereuse est modéré.",
      "Le ratio de récupération adverse dite dangereuse est faible. ",
      "Le ratio de récupération adverse dite dangereuse est très faible.",
    ],
    duels: [
      "La proportion de duels est vraiment trop faible pour espérer récupérer un nombre de ballons conséquent.",
      "La proportion de duels est trop faible pour espérer récupérer un nombre de ballons conséquent.",
      "La proportion de duels est mitigée et pour espérer récupérer un nombre de ballons conséquent.",
      "La proportion de duels est forte et facilite la récupération du ballon.",
      "La proportion de duels est très forte et facilite la récupération du ballon.",
    ],
    duelsRatio: [
      "Le ratio d’efficacité n’est vraiment pas à la hauteur !",
      "Le ratio d’efficacité n’est pas à la hauteur !",
      "Le ratio d’efficacité est moyennement satisfaisant !",
      "Le ratio d’efficacité est satisfaisant !",
      "Le ratio d’efficacité est très satisfaisant !",
    ],
    defensiveDuelsRatio: [
      "La solidité défensive est trop perfectible, car seulement une très petite partie des duels sont gagnés par les joueurs.",
      "La solidité défensive est perfectible, car seulement une petite partie des duels sont gagnés par les joueurs.",
      "La solidité défensive est insuffisante, car seulement une partie des duels sont gagnés par les joueurs.",
      "La solidité défensive est bonne, car une majorité des duels sont gagnés par les joueurs.",
      "La solidité défensive est trés bonne, car une grande majorité des duels sont gagnés par les joueurs.",
    ],
    offensiseDuelsRatio: [
      "Les joueurs sont faibles techniquement, car ils perdent trop souvent le ballon dans leurs duels offensifs.",
      "Les joueurs sont faibles techniquement, car ils perdent souvent le ballon dans leurs duels offensifs.",
      "Les joueurs perdent quelques ballons dans leurs duels offensifs.",
      "Les joueurs gagnent régulièrement leurs duels offensifs et gardent la possession du ballon.",
      "Les joueurs gagnent très régulièrement leurs duels offensifs et gardent la possession du ballon.",
    ],
    aerialDuelsRatio: [
      "Le timming dans les duels aériens est mauvais, car ils sont très souvent gagnés par les joueurs adverses.",
      "Le timming dans les duels aériens est mauvais, car ils sont souvent gagnés par les joueurs adverses.",
      "Le timming dans les duels aériens est moyennement bon, car ils sont autant de fois gagnés que perdus.",
      "Le timming dans les duels aériens est bon, car ils sont souvent à l’avantage de l’équipe.",
      "Le timming dans les duels aériens est excellent, car ils sont très souvent à l’avantage de l’équipe.",
    ],
    slidingTacklesRatio: [
      "L’excès d’engagement dans les tacles est vraiment trop pénalisant, car trop de fautes sont sifflées. ",
      "L’excès d’engagement dans les tacles est vraiment pénalisant, car trop de fautes sont sifflées. ",
      "Les tacles réalisés entrainent autant de fautes sifflées que d’actions avortées pour les adversaires.",
      "Les tacles sont bien maitrisés et permettent d’avorter les actions adverses ou de récupérer le ballon.. ",
      "Les tacles sont très bien maitrisés et permettent d’avorter les actions adverses ou de récupérer le ballon.",
    ],
    groundDuelsRatio: [
      "Le manque d’agressivité est trop pénalisant pour espérer gagner les duels au sol.",
      "Le manque d’agressivité est pénalisant pour espérer gagner les duels au sol.",
      "Les joueurs font preuve d’une agressivité modérée et remportent quelques duels au sol.",
      "Les joueurs font preuve d’une bonne agressivité et remportent beaucoup de leurs duels au sol.",
      "Les joueurs font preuve d’une très bonne agressivité et remportent énormément de duels au sol.",
    ],
    looseBallDuelsRatio: [
      "Les joueurs manquent terriblement de vivacité pour pouvoir récupérer un nombre signifiant de ballons.",
      "Les joueurs manquent de vivacité pour pouvoir récupérer un nombre signifiant de ballons.",
      "Les joueurs sont autant réactifs que les adversaires pour pouvoir récupérer autant de ballons qu’eux.",
      "Les joueurs sont réactifs et récupèrent un nombre signifiant de ballons.",
      "Les joueurs sont très réactifs et récupèrent un nombre signifiant de ballons.",
    ],
    dribblesAgainstRatio: [
      "Les joueurs se font très souvent dribbler lorsqu’ils se retrouvent seul face à un adversaires.",
      "Les joueurs se font souvent dribbler lorsqu’ils se retrouvent seul face à un adversaires.",
      "Les joueurs se font modérément dribbler lorsqu’ils se retrouvent seul face à un adversaires.",
      "Les joueurs se font rarement dribbler lorsqu’ils se retrouvent seul face à un adversaires.",
      "Les joueurs ne se font que très rarement dribbler lorsqu’ils se retrouvent seul face à un adversaires.",
    ],
    opponentOffsides: [
      "L’alignement défensif est beaucoup trop approximatif pour mettre les adversaires en position de hors-jeu",
      "L’alignement défensif est trop approximatif pour mettre les adversaires en position de hors-jeu",
      "L’alignement défensif est approximatif pour mettre les adversaires en position de hors-jeu",
      "L’alignement défensif est précis et permet de mettre régulièrement les adversaires en position de hors-jeu",
      "L’alignement défensif est précis et permet de mettre très régulièrement les adversaires en position de hors-jeu",
    ],
  },
  FREEKICKS: {
    cornersRatio: [
      "Les corners sont très mal négociés, car seulement un très petit nombre aboutissent à une action dangereuse",
      "Les corners sont mal négociés, car seulement un petit nombre aboutissent à une action dangereuse",
      "Les corners sont moyennement bien négociés, car seulement quelques-uns aboutissent à une action dangereuse",
      "Les corners sont bien négociés, car un grand nombre aboutissent à une action dangereuse",
      "Les corners sont très bien négociés, car un trés grand nombre aboutissent à une action dangereuse ",
    ],
    freekicksRatio: [
      "Les opportunités sont trop souvent gâchées par le peu de coups francs cadrés",
      "Les opportunités de marquer sont souvent gâchées par le manque de coups francs cadrés",
      "Les opportunités de marquer sont faiblement gagnantes, car seulement quelques coups francs sont cadrés",
      "Les opportunités de marquer sont souvent gagnantes, car la plupart des coups francs sont cadrés",
      "Les opportunités de marquer sont très souvent gagnantes, car la majorité des coups francs sont cadrés",
    ],
    directFreeKicksRatio: [
      "Le manque d’un spécialiste en la matière est très frappant",
      "Le manque d’un spécialiste en la matière est frappant",
      "Le ou les tireurs sont moyennement performants",
      "Le ou les tireurs sont très performants",
      "Le ou les tireurs sont extrêmement performants",
    ],
    freeKicksWithShotRatio: [
      "Très peu de coups francs d’attaques entrainent une action dangereuse pour l’équipe adverse.",
      "Peu de coups francs d’attaques entrainent une action dangereuse pour l’équipe adverse.",
      "Quelques coups francs d’attaques entrainent une action dangereuse pour l’équipe adverse.",
      "Une majorité de coups francs d’attaques entrainent une action dangereuse pour l’équipe adverse.",
      "Une grande majorité de coups francs d’attaques entrainent une action dangereuse pour l’équipe adverse.",
    ],
  },
  OFFENSIVE_BALANCE: {
    AttacksProportions: [
      "L’animation offensive du jeu montre que X % des attaques viennent du côté gauche contre X % du côté droit et X % du milieu du terrain",
    ],
    CrossesProportion: [
      "Parmi la totalité des centres réalisés par l’équipe X % viennent du côté droit contre X % du côté gauche",
    ],
    CrossesFromRightFlankRatio: [
      "Lorsque les centres viennent de la droite, le danger dans la surface de réparation est trop faible, car X % des ballons trouvent un partenaire à la réception",
      "Lorsque les centres viennent de la droite, le danger dans la surface de réparation est faible, car X % des ballons trouvent un partenaire à la réception",
      "Lorsque les centres viennent de la droite, le danger dans la surface de réparation est modéré, car X % des ballons trouvent un partenaire à la réception",
      "Lorsque les centres viennent de la droite, le danger dans la surface de réparation est réel, car X % des ballons trouvent un partenaire à la réception",
      "Lorsque les centres viennent de la droite, le danger dans la surface de réparation est omniprésent, car X % des ballons trouvent un partenaire à la réception",
    ],
    CrossesFromLeftFlankRatio: [
      "Lorsque les centres viennent de la gauche, le pourcentage de réussite de X % est un vrai handicape offensif, car très peu d’occasions de but sont crées ",
      "Lorsque les centres viennent de la gauche, le pourcentage de réussite de X % est un handicape offensif, car très peu d’occasions de but sont crées ",
      "Lorsque les centres viennent de la gauche, le pourcentage de réussite de X % est moyennement efficace, car très peu d’occasions de but sont crées ",
      "Lorsque les centres viennent de la gauche, le pourcentage de réussite de X % est vrai atout offensif, car des occasions de but sont crées ",
      "Lorsque les centres viennent de la gauche, le pourcentage de réussite de X % est excellent atout offensif, car des occasions de but sont crées ",
    ],
  },
  DEFENSIVE_BALANCE: {
    DefensiveProportion: [
      "L’animation défensive du jeu montre que X % des attaques viennent du côté gauche contre X % du côté droit et X % du milieu du terrain",
    ],
    CrossesProportion: [
      "Les adversaires réalisent en moyenne X % des centres de la droite contre X % de la gauche",
    ],
    CrossesRatio: [
      "Les défenseurs sont beaucoup trop faibles au niveau du marquage individuel, car la défense est souvent mise en danger par les centres des adversaires qui ont un taux de réussite de X %",
      "Les défenseurs sont beaucoup faibles au niveau du marquage individuel, car la défense est souvent mise en danger par les centres des adversaires qui ont un taux de réussite de X %",
      "Les défenseurs sont faibles au niveau du marquage individuel, car la défense est souvent mise en danger par les centres des adversaires qui ont un taux de réussite de X %",
      "Les défenseurs sont bons au niveau du marquage individuel, car la défense n’est pas souvent mise en danger par les centres des adversaires qui ont un taux de réussite de seulement X %",
      "Les défenseurs sont très bons au niveau du marquage individuel, car la défense n’est presque jamais mise en danger par les centres des adversaires qui ont un taux de réussite de seulement X %",
    ],
  },
  POSSESSION: {
    groupPossession: [
      "L’équipe à une possession trop stérile du ballon, elle n’impose pas suffisamment de pression sur les adversaires qui ont même des opportunités en contre.",
      "L’équipe à une possession stérile du ballon, elle n’impose pas suffisamment de pression sur les adversaires qui ont même des opportunités en contre.",
      "L’équipe à une possession moyennement bénéfique du ballon, elle impose une pression trop intermittente sur les adversaires qui ont même quelques opportunités en contre.",
      "L’équipe à une possession bénéfique du ballon, elle impose une pression intense aux adversaires qui n’arrivent pas à ressortir en contre.",
      "L’équipe à une possession très bénéfique du ballon, elle impose une pression très intense aux adversaires qui n’arrivent pas à ressortir en contre.",
    ],
    groupOpponentPossession: [
      "Lorsque la possession est fortement à l’avantage des adversaires, l’équipe n’arrive pas à maximiser ses temps forts et/ou par se montrer dangereuse en contre-attaque.",
      "Lorsque la possession est à l’avantage des adversaires, l’équipe n’arrive pas à maximiser ses temps forts et/ou par se montrer dangereuse en contre-attaque.",
      "Lorsque la possession est à l’avantage des adversaires, l’équipe arrive moyennement à maximiser ses temps forts et/ou par se montrer dangereuse en contre-attaque.",
      "Lorsque la possession est à l’avantage des adversaires, l’équipe arrive fréquemment à maximiser ses temps forts et/ou par se montrer dangereuse en contre-attaque.",
      "Lorsque la possession est à l’avantage des adversaires, l’équipe arrive très fréquemment à maximiser ses temps forts et/ou par se montrer dangereuse en contre-attaque.",
    ],
  },
};

export const TPI_TRANSLATION = {
  OFFENSIF: {
    goals: "Buts",
    goalConversion: "Efficacité",
    shots: "Tirs",
    shotsRatio: "Tirs",
    offensiveDuels: "Duels offensifs",
    offensiveDuelsRatio: "Duels offensifs",
    clearances: "Dégagement",
    shotsBlocked: "Tirs contrés",
    headShots: "Tirs",
    headShotsRatio: "Tirs",
    shotsOutsideConfidence: "Tirs",
    shotsOutsideRatio: "Tirs",
    cleanSheets: "Clean Sheets",
  },
  DEFENSIF: {
    concededGoals: "Buts",
    shotsAgainst: "Tirs",
    penalties: "Penalties",
    clearances: "Dégagement",
    shotsBlocked: "Tirs contrés",
    cleanSheets: "Clean Sheets",
    headShotsConfidence: "Tirs",
    gkSaves: "Intervention du gardien",
    gkAerialDuels: "Intervention du gardien",
    gkAerialDuelsRatio: "Intervention du gardien",
  },
  DISTRIBUTION: {
    passes: "Passes",
    passesRatio: "Passes",
    sumAssists: "Passes décisives",
    smartThroughPasses: "Passes créatives",
    smartThroughPassesRatio: "Passes créatives",
    keyPasses: "Passes clefs",
    keyPassesRatio: "Passes clefs",
    crosses: "Centres",
    crossesRatio: "Centres",
    pppd: "Passes dangereuses",
    pppdRatio: "Passes dangereuses",
    longPasses: "Passes longues",
    longPassesRatio: "Passes longues",
    forwardPasses: "Passes en avant",
    forwardPassesRatio: "Passes en avant",
    lateralPasses: "Passes laterales",
    lateralPassesRatio: "Passes laterales",
    backPasses: "Passes en retrait",
    backPassesRatio: "Passes en retrait",
    matchTempo: "Vitesse de transmission",
  },
  PERCUSSION: {
    dribbles: "Dribbles",
    dribblesRatio: "Dribbles",
    dribbleDistanceFromOpponentGoal: "Dribbles",
    progressiveRunByAccelation: "Accélérations",
  },
  RECOVERY: {
    challengeIntensity: "Intensité des défis",
    interceptions: "Interceptions",
    pressingDuels: "Pressing",
    counterpressingRecoveries: "Contre Pressing",
    duelsRatio: "Duels",
    defensiveDuelsRatio: "Duels défensifs",
    aerialDuelsRatio: "Duels aériens",
    slidingTacklesRatio: "Tacles",
    looseBallDuelsRatio: "Ballons Perdus",
    dribblesAgainstRatio: "Dribbles",
    sumOpponentHalfRecoveries: "Récupérations",
    foulsSuffered: "Fautes",
    recoveries: "Récupérations",
    opponentOffsides: "Hors-jeu",
  },
  PRESSING: {
    interceptions: "Interceptions",
    duelsRatio: "Duels",
    recoveries: "Récupérations",
    missedBalls: "Fautes Technique",
    losses: "Ballons Perdus",
    fouls: "Fautes",
    offsides: "Hors-jeu",
  },
  FREEKICKS: {
    penalties: "Penalties",
    penaltiesConversion: "Penalties",
    corners: "Corners",
    cornersRatio: "Corners",
    sumFreekicks: "Coups Francs",
    freekicksRatio: "Coups Francs",
    directFreeKicksRatio: "Coups Francs",
    freeKicksWithShotRatio: "Coups Francs",
  },
  POSSESSION: {
    purePossessionTime: "Possession",
    possessionNumber: "Possession",
    avgPossessionDuration: "Possession",
    possessionPercent: "Possession",
  },
};
